import { slugify } from "./seo";

export interface Comparison {
  slug: string;
  competitor: string;
  tagline: string;
  theirPricing: string;
  polysimPricing: string;
  intro: string;
  rows: { feature: string; polysim: string; them: string }[];
  theirStrengths: string[];
  theirWeaknesses: string[];
  verdict: string;
}

const P = "From $0 (free local) · $24/mo Independent Researcher";

const DATA: Comparison[] = [
  {
    slug: slugify("simscale"),
    competitor: "SimScale",
    tagline: "Browser CAE, but engineering-only and quote-gated.",
    theirPricing: "Free Community tier; Mechanical/Professional/Enterprise are quote-only.",
    polysimPricing: P,
    intro: "SimScale pioneered browser-based CAE, but everything above the free tier is hidden behind 'request a quote,' and it covers only engineering physics. PolySim publishes flat pricing, spans physics/bio/chem/math, and adds an AI copilot and surrogate models.",
    rows: [
      { feature: "Runs in browser", polysim: "Yes (WebGPU)", them: "Yes" },
      { feature: "Transparent pricing", polysim: "Yes, flat tiers", them: "No — quote only" },
      { feature: "Domains", polysim: "Physics, bio, chem, math, engineering", them: "Engineering CAE only" },
      { feature: "AI copilot (English → sim)", polysim: "Yes", them: "No" },
      { feature: "AI surrogate models", polysim: "Yes", them: "No" },
      { feature: "Free tier", polysim: "Free forever locally", them: "Limited core-hours" },
    ],
    theirStrengths: ["Mature, validated CAE solvers", "Large engineering community", "Established brand"],
    theirWeaknesses: ["Opaque quote-only pricing", "Engineering-only scope", "No generative AI authoring"],
    verdict: "Choose PolySim for transparent pricing, multi-domain scope, and AI-native authoring; choose SimScale if you need a specific validated legacy CAE workflow today.",
  },
  {
    slug: slugify("ansys"),
    competitor: "Ansys",
    tagline: "Industry titan, but desktop-heavy and expensive.",
    theirPricing: "Quote-only; seats commonly run thousands to six figures per year.",
    polysimPricing: P,
    intro: "Ansys is the gold standard for high-fidelity enterprise simulation, but it's desktop-first, costly, and steep to learn. PolySim brings a large share of that capability to the browser at a fraction of the cost, with AI assistance built in.",
    rows: [
      { feature: "Runs in browser", polysim: "Yes", them: "Mostly desktop" },
      { feature: "Entry cost", polysim: "$0–$24/mo", them: "$$$$ / quote" },
      { feature: "Learning curve", polysim: "Gentle, AI-assisted", them: "Steep" },
      { feature: "Setup time", polysim: "Seconds", them: "Install + license" },
      { feature: "AI copilot", polysim: "Yes", them: "Limited" },
    ],
    theirStrengths: ["Best-in-class fidelity", "Vast solver breadth", "Deep validation & certification"],
    theirWeaknesses: ["Very expensive", "Desktop-bound", "Long onboarding"],
    verdict: "Choose PolySim for accessible, fast, AI-assisted simulation and prototyping; Ansys still leads for certified, mission-critical enterprise analysis.",
  },
  {
    slug: slugify("comsol"),
    competitor: "COMSOL Multiphysics",
    tagline: "Great multiphysics — priced per module, per seat.",
    theirPricing: "Base ~$3,495/yr commercial; each add-on module $600–$4,500.",
    polysimPricing: P,
    intro: "COMSOL is beloved for multiphysics, but its per-module pricing balloons quickly and it's a desktop install. PolySim offers browser multiphysics with flat pricing and no module tax.",
    rows: [
      { feature: "Multiphysics", polysim: "Yes", them: "Yes (per module)" },
      { feature: "Per-module fees", polysim: "None", them: "$600–$4,500 each" },
      { feature: "Browser-native", polysim: "Yes", them: "No" },
      { feature: "AI copilot", polysim: "Yes", them: "No" },
      { feature: "Annual base cost", polysim: "$0–$288/yr", them: "$3,495+/yr" },
    ],
    theirStrengths: ["Excellent multiphysics coupling", "Mature model library", "Strong academic base"],
    theirWeaknesses: ["Per-module cost explosion", "Desktop install", "No real-time browser render"],
    verdict: "Choose PolySim to avoid module fees and work in the browser; COMSOL wins when you need its specific validated module ecosystem.",
  },
  {
    slug: slugify("matlab"),
    competitor: "MATLAB / Simulink",
    tagline: "Powerful production numerics — but paid, code-first, and desktop-anchored.",
    theirPricing: "Student Suite $119/yr; commercial per-toolbox runs into thousands.",
    polysimPricing: P,
    intro: "MATLAB and Simulink are a numerical powerhouse for production engineering — but you write code, you install, and you pay per toolbox. PolySim covers the same ground people reach for in teaching, exploration, and prototyping — linear algebra, numerical methods, signal processing, control systems, image processing, and a Simulink-style block simulator — free in the browser, with live equations and one-click code export.",
    rows: [
      { feature: "Block-diagram simulation", polysim: "Yes — free", them: "Simulink (paid add-on)" },
      { feature: "Control / DSP / linear algebra", polysim: "Interactive tools, free", them: "Toolboxes (paid)" },
      { feature: "Symbolic math", polysim: "Built in", them: "Symbolic Toolbox (paid)" },
      { feature: "Browser-native", polysim: "Yes", them: "Limited (MATLAB Online)" },
      { feature: "AI copilot", polysim: "Yes", them: "Limited" },
      { feature: "Toolbox fees", polysim: "None", them: "Per toolbox" },
    ],
    theirStrengths: ["Validated, production-grade toolboxes", "Code generation & hardware deployment", "Mature language & huge ecosystem"],
    theirWeaknesses: ["Paid license + per-toolbox fees", "Code-first learning curve", "Desktop-anchored, install required"],
    verdict: "Choose PolySim for free, interactive, browser-based simulation, teaching, and prototyping across the common toolbox areas; MATLAB and Simulink remain the choice for production-grade, certified engineering, code generation, and heavy custom programming.",
  },
  {
    slug: slugify("wolfram-mathematica"),
    competitor: "Wolfram / Mathematica",
    tagline: "Symbolic king — but niche syntax and no real-time render.",
    theirPricing: "Perpetual ~$3,445; annual subscriptions; students discounted.",
    polysimPricing: P,
    intro: "Mathematica excels at symbolic computation, but its language is niche and it isn't a real-time simulation renderer. PolySim pairs a symbolic engine with live 2D/3D solvers and AI authoring.",
    rows: [
      { feature: "Symbolic algebra", polysim: "Yes (CAS)", them: "Yes (best-in-class)" },
      { feature: "Real-time 3D sim", polysim: "Yes", them: "Limited" },
      { feature: "Browser-native", polysim: "Yes", them: "Cloud add-on" },
      { feature: "Entry cost", polysim: "$0–$24/mo", them: "$$$" },
      { feature: "AI copilot", polysim: "Yes", them: "Some" },
    ],
    theirStrengths: ["Unmatched symbolic depth", "Computable knowledge base", "Rich documentation"],
    theirWeaknesses: ["Steep, niche syntax", "Costly", "Not a real-time sim renderer"],
    verdict: "Choose PolySim for interactive simulation with symbolic support; Mathematica leads for pure, advanced symbolic work.",
  },
  {
    slug: slugify("luminary-cloud"),
    competitor: "Luminary Cloud",
    tagline: "Cloud CAE for enterprises — no consumer path.",
    theirPricing: "Consumption-based, quote-driven; enterprise focus.",
    polysimPricing: P,
    intro: "Luminary Cloud brings usage-based cloud CFD to enterprises. PolySim serves the same speed ethos but adds self-serve pricing, multi-domain scope, and an education tier.",
    rows: [
      { feature: "Self-serve signup", polysim: "Yes", them: "Sales-led" },
      { feature: "Education tier", polysim: "Yes", them: "No" },
      { feature: "Domains", polysim: "Multi-domain", them: "CFD-focused" },
      { feature: "Free tier", polysim: "Yes", them: "No" },
    ],
    theirStrengths: ["Fast cloud CFD", "AI design copilot", "Enterprise-grade"],
    theirWeaknesses: ["Enterprise-only", "Narrow domain", "No free/education path"],
    verdict: "Choose PolySim for self-serve, multi-domain, and education; Luminary suits large aerospace/automotive CFD teams.",
  },
  {
    slug: slugify("flexcompute"),
    competitor: "Flexcompute (Flow360 / Tidy3D)",
    tagline: "Fast GPU CFD & photonics — credits only, narrow scope.",
    theirPricing: "Pay-per-simulation FlexCredits.",
    polysimPricing: P,
    intro: "Flexcompute delivers blazing GPU CFD and photonics via credits, but it's narrow and credit-metered. PolySim spans many domains with flat plans plus optional compute tokens.",
    rows: [
      { feature: "Domains", polysim: "Multi-domain", them: "CFD + photonics" },
      { feature: "Flat subscription option", polysim: "Yes", them: "Credits only" },
      { feature: "Visual authoring", polysim: "Yes", them: "Code-driven" },
      { feature: "AI copilot", polysim: "Yes", them: "No" },
    ],
    theirStrengths: ["Very fast GPU solvers", "Strong photonics (Tidy3D)", "Accurate CFD"],
    theirWeaknesses: ["Narrow scope", "Credits-only pricing", "Code-first workflow"],
    verdict: "Choose PolySim for breadth and visual/AI authoring; Flexcompute wins for specialized high-end CFD or photonics.",
  },
  {
    slug: slugify("rescale"),
    competitor: "Rescale",
    tagline: "HPC brokerage — infrastructure, not an authoring tool.",
    theirPricing: "Consumption HPC; 1–3 year commitments discount.",
    polysimPricing: P,
    intro: "Rescale is a cloud-HPC layer for running other simulation apps. PolySim is the authoring tool itself, with its own solvers, AI copilot, and optional cloud compute.",
    rows: [
      { feature: "Authoring tool", polysim: "Yes", them: "No (runs others)" },
      { feature: "Own solvers", polysim: "Yes", them: "Third-party apps" },
      { feature: "AI copilot", polysim: "Yes", them: "No" },
      { feature: "Free tier", polysim: "Yes", them: "No" },
    ],
    theirStrengths: ["Huge app catalog", "Serious HPC scale", "Enterprise integrations"],
    theirWeaknesses: ["Not an authoring tool", "Enterprise pricing", "No free path"],
    verdict: "Use PolySim to build and run simulations directly; use Rescale to broker HPC for existing licensed solvers.",
  },
  {
    slug: slugify("physicsx"),
    competitor: "PhysicsX",
    tagline: "AI surrogate models — enterprise contracts only.",
    theirPricing: "Enterprise engagements (no self-serve).",
    polysimPricing: P,
    intro: "PhysicsX builds powerful AI surrogate models for large manufacturers under enterprise contracts. PolySim brings surrogate modeling to everyone, self-serve, in the browser.",
    rows: [
      { feature: "Self-serve surrogate", polysim: "Yes", them: "No" },
      { feature: "In-browser", polysim: "Yes", them: "No" },
      { feature: "Pricing", polysim: "$0–$24/mo", them: "Enterprise only" },
      { feature: "Full sim authoring", polysim: "Yes", them: "Surrogates only" },
    ],
    theirStrengths: ["State-of-the-art surrogates", "Deep enterprise partnerships", "Large physics models"],
    theirWeaknesses: ["No self-serve product", "No browser tool", "Enterprise-only"],
    verdict: "Choose PolySim for accessible surrogate modeling plus full authoring; PhysicsX suits large enterprises needing bespoke foundation models.",
  },
  {
    slug: slugify("phet"),
    competitor: "PhET / GeoGebra",
    tagline: "Great free education — but toy-grade and no cloud compute.",
    theirPricing: "Free (nonprofit/grants).",
    polysimPricing: P,
    intro: "PhET and GeoGebra are wonderful for teaching, but their simulations are fixed and limited. PolySim offers real, extensible solvers with a free education tier plus a path to research-grade compute.",
    rows: [
      { feature: "Editable/extensible sims", polysim: "Yes", them: "Fixed demos" },
      { feature: "Cloud compute", polysim: "Yes", them: "No" },
      { feature: "Research-grade solvers", polysim: "Yes", them: "No" },
      { feature: "Free education tier", polysim: "Yes", them: "Yes" },
    ],
    theirStrengths: ["Free and beloved in classrooms", "Simple and accessible", "Broad topic coverage"],
    theirWeaknesses: ["Fixed, toy-grade sims", "No cloud compute", "No research path"],
    verdict: "Choose PolySim when students and researchers need real, extensible simulation; PhET is ideal for simple introductory demonstrations.",
  },
  {
    slug: slugify("python-scipy"),
    competitor: "Python + SciPy / NumPy",
    tagline: "The free powerhouse — if you're willing to write the code.",
    theirPricing: "Free & open-source.",
    polysimPricing: P,
    intro: "Python with NumPy, SciPy, and Matplotlib is the free backbone of scientific computing, but every simulation starts from a blank file and a lot of boilerplate. PolySim gives you 390+ ready-to-run models with a UI, and — when you want the code — exports the exact Python for the model you're looking at, plus a built-in Pyodide console.",
    rows: [
      { feature: "Ready-made models", polysim: "390+ interactive", them: "Write your own" },
      { feature: "No setup / install", polysim: "Yes, in-browser", them: "pip / conda / venv" },
      { feature: "Exports runnable Python", polysim: "Yes (one click)", them: "It is Python" },
      { feature: "Full programmability", polysim: "Growing (console + export)", them: "Unlimited" },
      { feature: "Instant sharing/embedding", polysim: "Yes", them: "Notebook/repo" },
    ],
    theirStrengths: ["Unlimited flexibility", "Vast library ecosystem", "Free and ubiquitous"],
    theirWeaknesses: ["Everything is DIY", "Environment setup friction", "No turnkey interactive UI"],
    verdict: "Choose PolySim to explore and teach a model in seconds and leave with the Python; choose raw SciPy when you need full custom control and a production pipeline.",
  },
  {
    slug: slugify("octave"),
    competitor: "GNU Octave",
    tagline: "Free MATLAB syntax — same 1990s workflow.",
    theirPricing: "Free & open-source.",
    polysimPricing: P,
    intro: "Octave is the free, MATLAB-compatible option, and it's excellent if you already think in .m files. But it's still an install-and-script desktop environment. PolySim is interactive and browser-native, with hundreds of models you can run and adjust visually — and it exports MATLAB-compatible code when you want it.",
    rows: [
      { feature: "Runs in browser", polysim: "Yes", them: "Desktop install" },
      { feature: "Interactive UI models", polysim: "390+", them: "Scripts only" },
      { feature: "MATLAB-style code export", polysim: "Yes", them: "It is the syntax" },
      { feature: "Live equations + visuals", polysim: "Yes", them: "Plot commands" },
    ],
    theirStrengths: ["Free MATLAB compatibility", "Mature numeric core", "Scriptable"],
    theirWeaknesses: ["Desktop-bound", "No interactive UI", "Dated UX"],
    verdict: "Choose PolySim for instant, visual exploration; choose Octave when you need to run existing MATLAB scripts for free.",
  },
  {
    slug: slugify("desmos"),
    competitor: "Desmos",
    tagline: "Beautiful graphing — but graphing, not simulation.",
    theirPricing: "Free.",
    polysimPricing: P,
    intro: "Desmos is the best free graphing calculator on the web. But it graphs functions; it doesn't simulate dynamical systems, fluids, circuits, orbits, or PDEs. PolySim covers the graphing basics and adds 390+ time-stepping, physics-grade simulations.",
    rows: [
      { feature: "Function graphing", polysim: "Yes", them: "Best-in-class" },
      { feature: "Time-stepping simulation", polysim: "Yes (390+)", them: "No" },
      { feature: "Physics / ODE / PDE solvers", polysim: "Yes", them: "No" },
      { feature: "Code export", polysim: "Python/MATLAB/Julia", them: "No" },
    ],
    theirStrengths: ["Gorgeous, instant graphing", "Beloved in classrooms", "Free"],
    theirWeaknesses: ["No dynamical simulation", "No physical solvers", "Graphing only"],
    verdict: "Use Desmos to graph a function; use PolySim to simulate a system that evolves in time.",
  },
  {
    slug: slugify("geogebra"),
    competitor: "GeoGebra",
    tagline: "Superb interactive geometry & algebra — light on physics.",
    theirPricing: "Free (nonprofit).",
    polysimPricing: P,
    intro: "GeoGebra is outstanding for interactive geometry, algebra, and calculus visualization. PolySim complements it with real physical and engineering simulation — fluids, circuits, quantum, orbital mechanics — that GeoGebra isn't built for.",
    rows: [
      { feature: "Interactive geometry", polysim: "Some", them: "Best-in-class" },
      { feature: "Physics/engineering sims", polysim: "390+", them: "Limited" },
      { feature: "Cloud compute path", polysim: "Yes", them: "No" },
      { feature: "Code export", polysim: "Yes", them: "No" },
    ],
    theirStrengths: ["Excellent geometry & algebra", "Huge teacher community", "Free"],
    theirWeaknesses: ["Not a physics simulator", "No cloud compute", "No code export"],
    verdict: "Pair them: GeoGebra for geometry and algebra, PolySim for physical and engineering simulation.",
  },
  {
    slug: slugify("maple"),
    competitor: "Maplesoft Maple",
    tagline: "Strong symbolic math — desktop, licensed, per-seat.",
    theirPricing: "Commercial per-seat licenses; academic discounts.",
    polysimPricing: P,
    intro: "Maple is a powerful computer-algebra and technical-computing system, but it's a licensed desktop install. PolySim runs in the browser for free, includes a symbolic-math studio, and adds hundreds of interactive numerical simulations with one-click code export.",
    rows: [
      { feature: "Runs in browser", polysim: "Yes", them: "Desktop install" },
      { feature: "Entry cost", polysim: "$0", them: "Paid license" },
      { feature: "Symbolic math (CAS)", polysim: "Yes", them: "Best-in-class" },
      { feature: "Interactive simulations", polysim: "390+", them: "Some" },
    ],
    theirStrengths: ["Deep symbolic engine", "Mature technical computing", "Documentation"],
    theirWeaknesses: ["Licensed & desktop-bound", "Costly per seat", "Steeper onboarding"],
    verdict: "Choose PolySim for free, browser-native exploration and simulation; choose Maple for heavy symbolic-math workloads.",
  },
  {
    slug: slugify("julia"),
    competitor: "Julia (DifferentialEquations.jl)",
    tagline: "Blazing scientific code — still code-first.",
    theirPricing: "Free & open-source.",
    polysimPricing: P,
    intro: "Julia is a fantastic high-performance language for scientific computing and ODE/PDE work. Like Python, though, it's code-first with environment setup. PolySim gives you interactive, ready-to-run models in the browser and exports Julia when you want to drop into code.",
    rows: [
      { feature: "Ready-made interactive models", polysim: "390+", them: "Write your own" },
      { feature: "No install", polysim: "Yes", them: "Julia + packages" },
      { feature: "Exports Julia code", polysim: "Yes (one click)", them: "It is Julia" },
      { feature: "Raw performance", polysim: "In-browser", them: "Native, very fast" },
    ],
    theirStrengths: ["Excellent performance", "First-class ODE/PDE libraries", "Free & modern"],
    theirWeaknesses: ["Code-first", "Setup & compile times", "No turnkey UI"],
    verdict: "Explore in PolySim and export Julia; reach for Julia directly when you need maximum native performance.",
  },
  {
    slug: slugify("wolfram-alpha"),
    competitor: "Wolfram Alpha",
    tagline: "Great answers engine — not an interactive lab.",
    theirPricing: "Free basic; Pro ~$7.25/mo.",
    polysimPricing: P,
    intro: "Wolfram Alpha is a superb computational answer engine for one-shot queries. But it returns static results, not interactive, time-stepping simulations you can steer. PolySim is a live lab: adjust parameters, watch the system evolve, and take the code with you.",
    rows: [
      { feature: "One-shot computed answers", polysim: "Some", them: "Best-in-class" },
      { feature: "Interactive, steerable sims", polysim: "Yes (390+)", them: "No" },
      { feature: "Live parameter sliders", polysim: "Yes", them: "No" },
      { feature: "Code export", polysim: "Yes", them: "Limited" },
    ],
    theirStrengths: ["Vast curated knowledge", "Instant computed answers", "Broad coverage"],
    theirWeaknesses: ["Static results", "Not interactive/steerable", "No simulation loop"],
    verdict: "Use Wolfram Alpha to compute an answer; use PolySim to run and explore the system behind it.",
  },
  {
    slug: slugify("matlab-online"),
    competitor: "MATLAB Online",
    tagline: "MATLAB in a browser — but still behind a paid license.",
    theirPricing: "Requires a MATLAB license (Home ~$149, Student ~$49–$99, Standard ~$2,150/yr); browser access is included with the license.",
    polysimPricing: P,
    intro: "MATLAB Online runs the real MATLAB in your browser — powerful and industry-standard — but you still need a paid license, and it's a coding environment rather than a set of ready-to-run interactive simulators. PolySim needs no license or account to start, and every tool is a live, draggable simulation you can share as a link.",
    rows: [
      { feature: "Runs in browser", polysim: "Yes", them: "Yes" },
      { feature: "License required", polysim: "No — free to start", them: "Yes — paid" },
      { feature: "Ready-made interactive sims", polysim: "390+", them: "You build them in code" },
      { feature: "Live parameter sliders / drag", polysim: "Yes", them: "Via app-building only" },
      { feature: "Code export (Python/MATLAB/Julia)", polysim: "Yes", them: "MATLAB code" },
      { feature: "Cost to explore", polysim: "$0", them: "License" },
    ],
    theirStrengths: ["The real MATLAB language + toolboxes", "Industry-standard, validated", "No install"],
    theirWeaknesses: ["Requires a paid license", "Coding-first, not point-and-play", "Toolboxes cost extra"],
    verdict: "Choose MATLAB Online if you already have a license and need the MATLAB language; choose PolySim for free, instant, interactive simulations with nothing to install or buy.",
  },
  {
    slug: slugify("simulink"),
    competitor: "Simulink",
    tagline: "The block-diagram standard — powerful, and priced like it.",
    theirPricing: "Add-on to MATLAB; Standard ~$3,600/yr, Home/Student tiers lower; requires a MATLAB license.",
    polysimPricing: P,
    intro: "Simulink is the gold standard for block-diagram modeling of dynamic systems — and it's superb. But it's a paid add-on on top of MATLAB, desktop-first, and heavy to get started. PolySim offers a browser-native visual block/graph editor plus hundreds of ready-to-run dynamic simulations, free, with nothing to install.",
    rows: [
      { feature: "Block-diagram modeling", polysim: "Yes (visual node graph)", them: "Yes — industry standard" },
      { feature: "Runs in browser", polysim: "Yes", them: "Desktop" },
      { feature: "Cost", polysim: "$0–$24/mo", them: "MATLAB + Simulink licenses" },
      { feature: "Setup", polysim: "Instant, in-browser", them: "Install + license" },
      { feature: "Ready-made dynamic sims", polysim: "Hundreds", them: "You build them" },
    ],
    theirStrengths: ["Deep, validated block library", "Code generation for embedded targets", "Industry adoption"],
    theirWeaknesses: ["Expensive (add-on to MATLAB)", "Desktop-bound", "Steep onboarding"],
    verdict: "Choose Simulink for production control-system engineering and code generation; choose PolySim to model, teach, and explore dynamic systems free in the browser.",
  },
  {
    slug: slugify("scilab"),
    competitor: "Scilab / Xcos",
    tagline: "Free and MATLAB-like — but desktop, and dated UX.",
    theirPricing: "Free and open-source.",
    polysimPricing: P,
    intro: "Scilab is a capable free, open-source MATLAB alternative, and Xcos mirrors Simulink for block diagrams. Both are genuinely free — but they're desktop installs with an older interface and no ready-made interactive library. PolySim runs in the browser with hundreds of live simulators and an AI copilot.",
    rows: [
      { feature: "Price", polysim: "Free locally", them: "Free (open-source)" },
      { feature: "Runs in browser", polysim: "Yes", them: "No — desktop install" },
      { feature: "Ready-made interactive sims", polysim: "390+", them: "Build in code/Xcos" },
      { feature: "Modern UI + sharing", polysim: "Yes, shareable links", them: "Dated desktop UI" },
      { feature: "AI copilot", polysim: "Yes", them: "No" },
    ],
    theirStrengths: ["Genuinely free & open-source", "MATLAB-like language", "Xcos block modeling"],
    theirWeaknesses: ["Desktop install only", "Older user experience", "Smaller ecosystem"],
    verdict: "Choose Scilab if you want a free desktop MATLAB clone and scripting; choose PolySim for free browser-native, ready-to-run interactive simulation.",
  },
  {
    slug: slugify("labview"),
    competitor: "LabVIEW",
    tagline: "Graphical instrumentation — hardware-focused and pricey.",
    theirPricing: "Community edition free (non-commercial); Base/Full/Pro subscriptions roughly $500–$5,000+/yr.",
    polysimPricing: P,
    intro: "LabVIEW is a graphical dataflow environment built for test, measurement, and hardware control with NI instruments. It's excellent for that niche but expensive and hardware-tied. PolySim shares the visual-dataflow idea but focuses on free, browser-based scientific simulation across many domains.",
    rows: [
      { feature: "Visual dataflow programming", polysim: "Yes (node graph)", them: "Yes" },
      { feature: "Runs in browser", polysim: "Yes", them: "Desktop" },
      { feature: "Hardware/instrument I/O", polysim: "No (simulation focus)", them: "Yes — its core strength" },
      { feature: "Entry cost", polysim: "$0", them: "Free (non-commercial) → $$$" },
      { feature: "Multi-domain science sims", polysim: "390+", them: "Limited" },
    ],
    theirStrengths: ["Best-in-class hardware/DAQ integration", "Mature graphical dataflow", "Real-time & FPGA targets"],
    theirWeaknesses: ["Expensive for commercial use", "Hardware-centric", "Desktop-bound"],
    verdict: "Choose LabVIEW to acquire and control physical instruments; choose PolySim for free, browser-based simulation and teaching.",
  },
  {
    slug: slugify("ltspice"),
    competitor: "LTspice",
    tagline: "Free SPICE circuits — but desktop and circuits-only.",
    theirPricing: "Free (Analog Devices).",
    polysimPricing: P,
    intro: "LTspice is a fast, free, industry-trusted SPICE circuit simulator — unbeatable for analog circuit design on the desktop. But it's Windows/desktop-first and covers only electronics. PolySim runs in any browser and spans circuits plus physics, math, controls, DSP, and more.",
    rows: [
      { feature: "Price", polysim: "Free locally", them: "Free" },
      { feature: "Runs in browser", polysim: "Yes", them: "No — desktop app" },
      { feature: "Scope", polysim: "Circuits + physics/math/DSP/controls", them: "Analog/mixed circuits only" },
      { feature: "Shareable links & embeds", polysim: "Yes", them: "No" },
      { feature: "Interactive sliders", polysim: "Yes", them: "Parameter sweeps" },
    ],
    theirStrengths: ["Fast, accurate SPICE engine", "Huge device library", "Trusted by EEs"],
    theirWeaknesses: ["Desktop-only", "Electronics-only", "No browser/sharing"],
    verdict: "Choose LTspice for serious analog circuit design; choose PolySim for browser-based, multi-domain simulation and teaching that includes circuits.",
  },
  {
    slug: slugify("symbolab"),
    competitor: "Symbolab",
    tagline: "Step-by-step math solver — answers, not simulations.",
    theirPricing: "Free basic; Pro roughly $2–$7/mo.",
    polysimPricing: P,
    intro: "Symbolab is a popular step-by-step math solver that's great for checking homework algebra and calculus. But it returns worked answers, not interactive, time-stepping systems you can steer. PolySim complements it with a live lab: watch dynamics evolve, drag parameters, and export runnable code.",
    rows: [
      { feature: "Step-by-step algebra/calculus", polysim: "Some (CAS)", them: "Best-in-class" },
      { feature: "Interactive simulations", polysim: "Yes (390+)", them: "No" },
      { feature: "Live parameter sliders / drag", polysim: "Yes", them: "No" },
      { feature: "Runnable code export", polysim: "Yes", them: "No" },
    ],
    theirStrengths: ["Excellent step-by-step solutions", "Huge coverage of math problems", "Student-friendly"],
    theirWeaknesses: ["Static answers, not simulations", "No interactive systems", "Paywalled steps"],
    verdict: "Use Symbolab to solve an equation step by step; use PolySim to see and explore the system that equation describes.",
  },
  {
    slug: slugify("openmodelica"),
    competitor: "OpenModelica",
    tagline: "Free system modeling — powerful, but a steep desktop tool.",
    theirPricing: "Free and open-source.",
    polysimPricing: P,
    intro: "OpenModelica is a free, open-source implementation of the Modelica language for equation-based, multi-domain system modeling — very powerful for physical system design. It's also a desktop tool with a real learning curve. PolySim trades some depth for instant, browser-based, interactive accessibility across hundreds of ready-made models.",
    rows: [
      { feature: "Price", polysim: "Free locally", them: "Free (open-source)" },
      { feature: "Runs in browser", polysim: "Yes", them: "No — desktop install" },
      { feature: "Equation-based system modeling", polysim: "Node graph + solvers", them: "Yes — Modelica language" },
      { feature: "Ready-made interactive sims", polysim: "390+", them: "Build in Modelica" },
      { feature: "Learning curve", polysim: "Gentle, AI-assisted", them: "Steep" },
    ],
    theirStrengths: ["Powerful equation-based modeling", "Multi-domain (thermal/mechanical/electrical)", "Free & open"],
    theirWeaknesses: ["Steep learning curve", "Desktop-bound", "No ready-made interactive library"],
    verdict: "Choose OpenModelica for rigorous equation-based system modeling; choose PolySim for instant, interactive, browser-based simulation and teaching.",
  },
  {
    slug: slugify("mathcad"),
    competitor: "PTC Mathcad",
    tagline: "Engineering calculations — paid, desktop, single-domain.",
    theirPricing: "Subscription roughly $400–$700/yr; free Mathcad Express with limits.",
    polysimPricing: P,
    intro: "Mathcad is a respected engineering-calculation tool where math reads like a worksheet with live units. It's paid, desktop-first, and centered on calculations rather than dynamic simulation. PolySim renders live equations too, but as interactive, time-stepping simulations you can run free in the browser.",
    rows: [
      { feature: "Live math worksheets", polysim: "Live equations per sim", them: "Yes — its core" },
      { feature: "Runs in browser", polysim: "Yes", them: "Desktop" },
      { feature: "Interactive dynamic sims", polysim: "Yes (390+)", them: "Limited" },
      { feature: "Entry cost", polysim: "$0", them: "~$400–$700/yr" },
      { feature: "Unit-aware calculation", polysim: "Partial", them: "Yes — strong" },
    ],
    theirStrengths: ["Readable unit-aware worksheets", "Trusted for engineering docs", "Good for traceable calcs"],
    theirWeaknesses: ["Paid subscription", "Desktop-bound", "Not built for dynamic simulation"],
    verdict: "Choose Mathcad for documented, unit-aware engineering calculations; choose PolySim for free, interactive, browser-based simulation.",
  },
];

export const COMPARISONS = DATA;
export function getComparison(slug: string): Comparison | undefined {
  return COMPARISONS.find((c) => c.slug === slug);
}
export function getAllComparisonSlugs(): string[] {
  return COMPARISONS.map((c) => c.slug);
}
