import { slugify } from "./seo";

export interface EqModel {
  slug: string;
  name: string;
  formula: string; // plain-text math
  field: string;
  summary: string;
  detail: string;
  variables: { sym: string; meaning: string }[];
  studio?: string;
}

type Seed = [name: string, formula: string, field: string, summary: string, detail: string, variables: [string, string][], studio?: string];

const SEEDS: Seed[] = [
  ["Navier–Stokes Equations", "ρ(∂u/∂t + u·∇u) = −∇p + μ∇²u + f", "Fluid Dynamics",
    "The fundamental equations of viscous fluid motion.", "The Navier–Stokes equations express conservation of momentum for a fluid, balancing inertia against pressure, viscous, and body forces. Solving them underlies all of computational fluid dynamics.",
    [["u", "velocity field"], ["p", "pressure"], ["ρ", "density"], ["μ", "dynamic viscosity"], ["f", "body force"]], "/studio/fluid"],
  ["Lorenz System", "ẋ=σ(y−x), ẏ=x(ρ−z)−y, ż=xy−βz", "Chaos Theory",
    "A three-variable model that birthed chaos theory.", "Derived from atmospheric convection, the Lorenz system shows how simple deterministic equations produce unpredictable, aperiodic motion on a strange attractor.",
    [["σ", "Prandtl number"], ["ρ", "Rayleigh number"], ["β", "geometric factor"]], "/studio/dynamics"],
  ["SIR Model", "dS/dt=−βSI, dI/dt=βSI−γI, dR/dt=γI", "Epidemiology",
    "The compartmental model of infectious-disease spread.", "The SIR model partitions a population into susceptible, infected, and recovered compartments, with transmission rate β and recovery rate γ governing outbreak dynamics and herd immunity.",
    [["S", "susceptible fraction"], ["I", "infected fraction"], ["R", "recovered fraction"], ["β", "transmission rate"], ["γ", "recovery rate"]], "/studio/dynamics"],
  ["Lotka–Volterra Equations", "dx/dt=αx−βxy, dy/dt=δxy−γy", "Mathematical Biology",
    "Predator–prey population oscillations.", "The Lotka–Volterra equations model coupled prey and predator populations, producing sustained oscillations that shaped theoretical ecology.",
    [["x", "prey population"], ["y", "predator population"], ["α", "prey growth"], ["β", "predation"], ["γ", "predator death"], ["δ", "predator gain"]], "/studio/dynamics"],
  ["Schrödinger Equation", "iħ ∂ψ/∂t = Ĥψ", "Quantum Mechanics",
    "The governing equation of quantum states.", "The time-dependent Schrödinger equation describes how a quantum wavefunction evolves under a Hamiltonian, the foundation of all quantum mechanics.",
    [["ψ", "wavefunction"], ["ħ", "reduced Planck constant"], ["Ĥ", "Hamiltonian operator"]]],
  ["Heat Equation", "∂u/∂t = α∇²u", "Thermal / PDE",
    "Diffusion of heat through a medium.", "The heat equation is the prototypical parabolic PDE, describing how temperature diffuses over time and space with thermal diffusivity α.",
    [["u", "temperature"], ["α", "thermal diffusivity"]], "/studio/dynamics"],
  ["Wave Equation", "∂²u/∂t² = c²∇²u", "Waves / PDE",
    "Propagation of waves at speed c.", "The wave equation governs vibrations, sound, and light, relating a field's acceleration to its curvature through the wave speed c.",
    [["u", "displacement"], ["c", "wave speed"]]],
  ["Maxwell's Equations", "∇·E=ρ/ε₀, ∇·B=0, ∇×E=−∂B/∂t, ∇×B=μ₀J+μ₀ε₀∂E/∂t", "Electromagnetism",
    "The unified laws of electromagnetism.", "Maxwell's four equations describe how electric and magnetic fields are generated by charges and currents and how they propagate as light.",
    [["E", "electric field"], ["B", "magnetic field"], ["ρ", "charge density"], ["J", "current density"]]],
  ["Gray–Scott Model", "∂u/∂t=Dᵤ∇²u−uv²+F(1−u), ∂v/∂t=D_v∇²v+uv²−(F+k)v", "Reaction–Diffusion",
    "A reaction–diffusion system that forms Turing patterns.", "The Gray–Scott model of two reacting, diffusing chemicals produces spots, stripes, and self-replicating patterns depending on feed and kill rates.",
    [["u,v", "chemical concentrations"], ["F", "feed rate"], ["k", "kill rate"], ["Dᵤ,D_v", "diffusion rates"]], "/studio/dynamics"],
  ["Newton's Second Law", "F = ma", "Classical Mechanics",
    "Force equals mass times acceleration.", "Newton's second law relates the net force on a body to its acceleration, the starting point for nearly all of classical dynamics.",
    [["F", "net force"], ["m", "mass"], ["a", "acceleration"]], "/studio/particles"],
  ["Law of Universal Gravitation", "F = G m₁m₂ / r²", "Classical Mechanics",
    "The gravitational attraction between masses.", "Newton's law of gravitation gives the attractive force between two masses, inversely proportional to the square of their separation.",
    [["G", "gravitational constant"], ["m₁,m₂", "masses"], ["r", "separation"]], "/studio/particles"],
  ["Van der Pol Oscillator", "ẍ − μ(1−x²)ẋ + x = 0", "Nonlinear Dynamics",
    "A self-sustaining oscillator with a limit cycle.", "The Van der Pol equation models nonlinear damping that pumps energy at low amplitude and dissipates it at high amplitude, settling onto a stable limit cycle.",
    [["x", "state"], ["μ", "nonlinearity strength"]], "/studio/dynamics"],
  ["Black–Scholes Equation", "∂V/∂t + ½σ²S²∂²V/∂S² + rS∂V/∂S − rV = 0", "Quantitative Finance",
    "The PDE for pricing options.", "The Black–Scholes equation prices derivatives under geometric Brownian motion, a parabolic PDE solved across asset price and time.",
    [["V", "option value"], ["S", "asset price"], ["σ", "volatility"], ["r", "risk-free rate"]]],
  ["Poisson Equation", "∇²φ = −ρ/ε", "Fields / PDE",
    "Relates a potential to its source.", "The Poisson equation appears in electrostatics, gravitation, and incompressible flow, linking a potential field to a source distribution.",
    [["φ", "potential"], ["ρ", "source density"], ["ε", "permittivity"]]],
  ["Diffusion Equation (Fick's Second Law)", "∂c/∂t = D∇²c", "Transport",
    "How concentration spreads by diffusion.", "Fick's second law describes how a concentration field evolves under diffusion with coefficient D, central to mass transport and chemistry.",
    [["c", "concentration"], ["D", "diffusion coefficient"]], "/studio/fluid"],
  ["Bernoulli's Equation", "p + ½ρv² + ρgh = const", "Fluid Dynamics",
    "Energy conservation along a streamline.", "Bernoulli's principle relates pressure, velocity, and elevation in a steady, inviscid flow, explaining lift and venturi effects.",
    [["p", "pressure"], ["v", "velocity"], ["h", "height"], ["ρ", "density"]], "/studio/fluid"],
  ["Logistic Map", "xₙ₊₁ = r xₙ(1 − xₙ)", "Chaos Theory",
    "A simple map that routes to chaos.", "The logistic map is a one-line recurrence whose period-doubling cascade is a canonical route to chaos as the growth parameter r increases.",
    [["x", "population fraction"], ["r", "growth rate"]], "/studio/dynamics"],
  ["Damped Harmonic Oscillator", "mẍ + cẋ + kx = 0", "Mechanics / Vibration",
    "Oscillation with energy loss.", "The damped harmonic oscillator models springs and structures losing energy to damping, with under-, critical, and over-damped regimes.",
    [["m", "mass"], ["c", "damping"], ["k", "stiffness"]], "/studio/dynamics"],
  ["Continuity Equation", "∂ρ/∂t + ∇·(ρu) = 0", "Conservation Laws",
    "Conservation of mass in a flow.", "The continuity equation states that mass is neither created nor destroyed, tying density changes to the divergence of mass flux.",
    [["ρ", "density"], ["u", "velocity"]], "/studio/fluid"],
  ["Michaelis–Menten Kinetics", "v = Vmax[S] / (Km + [S])", "Enzyme Kinetics",
    "The rate law for enzyme-catalyzed reactions.", "Michaelis–Menten kinetics describes how reaction velocity saturates with substrate concentration, foundational in biochemistry.",
    [["v", "reaction rate"], ["Vmax", "max rate"], ["Km", "Michaelis constant"], ["[S]", "substrate"]]],
];

export const MODELS: EqModel[] = SEEDS.map((s) => {
  const [name, formula, field, summary, detail, variables, studio] = s;
  return { slug: slugify(name), name, formula, field, summary, detail, variables: variables.map(([sym, meaning]) => ({ sym, meaning })), studio };
});

export function getModel(slug: string): EqModel | undefined {
  return MODELS.find((m) => m.slug === slug);
}
export function getAllModelSlugs(): string[] {
  return MODELS.map((m) => m.slug);
}
