// The 200 Multi-Solvers: guided workflows that chain existing solvers end-to-end.
// Each `steps` entry is a real studio slug from the registry.
export type Multi = { s: string; n: string; p: string; t: string; steps: string[] };

export const PACKS = [
  "Structural & Geotechnical", "Fluids & Energy", "Electronics & Power", "Controls & Robotics",
  "Data & Statistics", "Finance & Quant", "Physics & Quantum", "Chemistry & Materials",
  "Earth & First Responders", "Biology & Aerospace", "Operations & Economics",
] as const;

export const MULTIS: Multi[] = [
  // ---- Structural & Geotechnical (1-20) ----
  { s: "bridge-designer", n: "Bridge Designer", p: "Structural & Geotechnical", t: "Full span from beam to foundation", steps: ["beam-deflection", "shear-moment", "column-buckling", "concrete-beam", "soil-bearing", "base-shear"] },
  { s: "multi-story-frame", n: "Multi-Story Frame", p: "Structural & Geotechnical", t: "Seismic frame design", steps: ["base-shear", "column-buckling", "beam-deflection", "mohrs-circle"] },
  { s: "steel-connection-designer", n: "Steel Connection Designer", p: "Structural & Geotechnical", t: "Bolted & welded joints", steps: ["shear-moment", "mohrs-circle", "fatigue"] },
  { s: "roof-truss-analyzer", n: "Roof Truss Analyzer", p: "Structural & Geotechnical", t: "Members, buckling, deflection", steps: ["fea", "column-buckling", "beam-deflection"] },
  { s: "crane-boom-check", n: "Crane Boom Check", p: "Structural & Geotechnical", t: "3D frame + fatigue", steps: ["fea-3d", "column-buckling", "fatigue"] },
  { s: "footfall-vibration", n: "Pedestrian Bridge Vibration", p: "Structural & Geotechnical", t: "Modes & comfort", steps: ["beam-deflection", "standing-waves"] },
  { s: "reinforced-slab", n: "Reinforced Slab Designer", p: "Structural & Geotechnical", t: "Flexure, shear, deflection", steps: ["concrete-beam", "beam-deflection", "shear-moment"] },
  { s: "wind-load-package", n: "Wind Load Package", p: "Structural & Geotechnical", t: "Pressure to base shear", steps: ["airfoil-polar", "base-shear", "beam-deflection"] },
  { s: "cantilever-balcony", n: "Cantilever Balcony", p: "Structural & Geotechnical", t: "Deflection & capacity", steps: ["beam-deflection", "concrete-beam"] },
  { s: "prestressed-girder", n: "Prestressed Girder", p: "Structural & Geotechnical", t: "Losses & fatigue", steps: ["concrete-beam", "beam-deflection", "fatigue"] },
  { s: "shallow-foundation", n: "Shallow Foundation Designer", p: "Structural & Geotechnical", t: "Bearing & settlement", steps: ["soil-bearing", "groundwater"] },
  { s: "retaining-structure-suite", n: "Retaining Structure Suite", p: "Structural & Geotechnical", t: "Pressure, sliding, bearing", steps: ["retaining-wall", "soil-bearing", "groundwater"] },
  { s: "slope-stability-kit", n: "Slope Stability Kit", p: "Structural & Geotechnical", t: "Static & seismic", steps: ["soil-bearing", "seismic", "groundwater"] },
  { s: "pile-foundation", n: "Pile Foundation", p: "Structural & Geotechnical", t: "Bearing & friction", steps: ["soil-bearing", "beam-deflection"] },
  { s: "excavation-shoring", n: "Excavation & Shoring", p: "Structural & Geotechnical", t: "Earth pressure & dewatering", steps: ["retaining-wall", "groundwater"] },
  { s: "liquefaction-assessment", n: "Liquefaction Assessment", p: "Structural & Geotechnical", t: "Seismic soil failure", steps: ["seismic", "soil-bearing"] },
  { s: "dam-seepage", n: "Dam Seepage", p: "Structural & Geotechnical", t: "Flow & uplift", steps: ["groundwater", "retaining-wall"] },
  { s: "embankment-settlement", n: "Embankment Settlement", p: "Structural & Geotechnical", t: "Consolidation & stability", steps: ["soil-bearing", "groundwater"] },
  { s: "tunnel-support", n: "Tunnel Support", p: "Structural & Geotechnical", t: "Ground load & lining", steps: ["beam-deflection", "soil-bearing"] },
  { s: "site-grading-runoff", n: "Site Grading & Runoff", p: "Structural & Geotechnical", t: "Drainage & detention", steps: ["groundwater", "spatial-interpolation"] },
  // ---- Fluids & Energy (21-40) ----
  { s: "airfoil-wing-lab", n: "Airfoil & Wing Lab", p: "Fluids & Energy", t: "Lift, drag, flow", steps: ["airfoil-polar", "fluid", "cfd-3d"] },
  { s: "pump-piping-system", n: "Pump & Piping System", p: "Fluids & Energy", t: "Friction, curve, cavitation", steps: ["fluid", "buoyancy"] },
  { s: "hvac-duct-designer", n: "HVAC Duct Designer", p: "Fluids & Energy", t: "Flow, fan, noise", steps: ["fluid", "sound-levels", "thermal-resistance"] },
  { s: "wind-turbine-yield", n: "Wind Turbine Yield", p: "Fluids & Energy", t: "Airfoil to annual energy", steps: ["airfoil-polar", "wind-power", "lcoe"] },
  { s: "heat-exchanger-sizing", n: "Heat Exchanger Sizing", p: "Fluids & Energy", t: "Flow & heat transfer", steps: ["fluid", "thermal-resistance", "heat-3d"] },
  { s: "nozzle-jet", n: "Nozzle & Jet", p: "Fluids & Energy", t: "Compressible flow & shock", steps: ["fluid", "mach-cone", "rocket"] },
  { s: "compressor-map", n: "Compressor Map", p: "Fluids & Energy", t: "Cycle & efficiency", steps: ["otto-cycle", "carnot-cycle"] },
  { s: "pipeline-network", n: "Pipeline Network", p: "Fluids & Energy", t: "Flow & routing", steps: ["fluid", "shortest-path"] },
  { s: "cooling-fan-selection", n: "Cooling Fan Selection", p: "Fluids & Energy", t: "Curve & noise", steps: ["fluid", "sound-levels"] },
  { s: "sail-hydrofoil", n: "Sail / Hydrofoil", p: "Fluids & Energy", t: "Lift & righting", steps: ["airfoil-polar", "buoyancy"] },
  { s: "building-energy-model", n: "Building Energy Model", p: "Fluids & Energy", t: "Envelope to annual energy", steps: ["thermal-resistance", "solar-panel", "heat-pump", "lcoe"] },
  { s: "solar-pv-system", n: "Solar PV System", p: "Fluids & Energy", t: "Yield, storage, payback", steps: ["solar-panel", "battery-storage", "lcoe"] },
  { s: "engine-thermo-lab", n: "Engine Thermo Lab", p: "Fluids & Energy", t: "Cycle & efficiency", steps: ["otto-cycle", "carnot-cycle"] },
  { s: "refrigeration-cycle", n: "Refrigeration Cycle", p: "Fluids & Energy", t: "COP & sizing", steps: ["heat-pump", "carnot-cycle"] },
  { s: "insulation-optimizer", n: "Insulation Optimizer", p: "Fluids & Energy", t: "R-value & payback", steps: ["thermal-resistance", "carbon-footprint"] },
  { s: "solar-thermal-collector", n: "Solar Thermal Collector", p: "Fluids & Energy", t: "Irradiance & losses", steps: ["solar-panel", "thermal-resistance"] },
  { s: "geothermal-heat-pump", n: "Geothermal Heat Pump", p: "Fluids & Energy", t: "Ground exchange & COP", steps: ["heat-pump", "thermal-resistance"] },
  { s: "battery-thermal", n: "Battery Thermal Management", p: "Fluids & Energy", t: "Heat & cooling", steps: ["battery-storage", "thermal-resistance"] },
  { s: "district-heating", n: "District Heating", p: "Fluids & Energy", t: "Loss & efficiency", steps: ["thermal-resistance", "lcoe"] },
  { s: "waste-heat-recovery", n: "Waste-Heat Recovery", p: "Fluids & Energy", t: "ORC power", steps: ["carnot-cycle", "otto-cycle", "lcoe"] },
  // ---- Electronics & Power (41-60) ----
  { s: "filter-amplifier-chain", n: "Filter + Amplifier Chain", p: "Electronics & Power", t: "Filter, op-amp, Bode", steps: ["filter-designer", "op-amp", "bode-plot", "aliasing"] },
  { s: "power-supply-designer", n: "Power Supply Designer", p: "Electronics & Power", t: "Rectify, filter, ripple", steps: ["rlc", "filter-designer", "thermal-resistance"] },
  { s: "rf-front-end", n: "RF Front End", p: "Electronics & Power", t: "LNA to link budget", steps: ["filter-designer", "transmission-line", "radio-range"] },
  { s: "sensor-signal-chain", n: "Sensor Signal Chain", p: "Electronics & Power", t: "Amp, ADC, noise", steps: ["op-amp", "aliasing", "fft"] },
  { s: "motor-driver", n: "Motor Driver", p: "Electronics & Power", t: "Motor, PID, bias", steps: ["dc-motor", "pid-control", "transistor-bias", "bode-plot"] },
  { s: "audio-amplifier", n: "Audio Amplifier", p: "Electronics & Power", t: "Gain, filter, power", steps: ["op-amp", "filter-designer", "sound-levels"] },
  { s: "oscillator-designer", n: "Oscillator Designer", p: "Electronics & Power", t: "Feedback & stability", steps: ["rlc", "bode-plot"] },
  { s: "pcb-thermal", n: "PCB Thermal", p: "Electronics & Power", t: "Dissipation & derating", steps: ["thermal-resistance"] },
  { s: "emi-filter", n: "EMI Filter", p: "Electronics & Power", t: "Attenuation & compliance", steps: ["filter-designer", "bode-plot"] },
  { s: "class-d-amp", n: "Class-D Amp", p: "Electronics & Power", t: "PWM, filter, THD", steps: ["aliasing", "filter-designer"] },
  { s: "power-system-analyzer", n: "Power System Analyzer", p: "Electronics & Power", t: "Three-phase to power factor", steps: ["three-phase", "transmission-line"] },
  { s: "load-flow-study", n: "Load Flow Study", p: "Electronics & Power", t: "Bus voltages & losses", steps: ["three-phase", "shortest-path"] },
  { s: "fault-analysis", n: "Fault Analysis", p: "Electronics & Power", t: "Short-circuit & protection", steps: ["three-phase", "rlc"] },
  { s: "grid-frequency-control", n: "Grid Frequency Control", p: "Electronics & Power", t: "Droop & inertia", steps: ["pid-control", "three-phase"] },
  { s: "microgrid-designer", n: "Microgrid Designer", p: "Electronics & Power", t: "Solar, battery, dispatch", steps: ["solar-panel", "battery-storage", "lcoe"] },
  { s: "ev-charging-impact", n: "EV Charging Impact", p: "Electronics & Power", t: "Load & transformer", steps: ["ev-efficiency", "three-phase", "battery-storage"] },
  { s: "transmission-sag", n: "Transmission Sag", p: "Electronics & Power", t: "Thermal & clearance", steps: ["thermal-expansion", "transmission-line"] },
  { s: "reactive-power-comp", n: "Reactive Power Comp", p: "Electronics & Power", t: "Power factor & voltage", steps: ["three-phase"] },
  { s: "renewable-integration", n: "Renewable Integration", p: "Electronics & Power", t: "Variability & storage", steps: ["wind-power", "solar-panel", "battery-storage"] },
  { s: "substation-grounding", n: "Substation Grounding", p: "Electronics & Power", t: "Fault current & safety", steps: ["three-phase"] },
  // ---- Controls & Robotics (61-70) ----
  { s: "robot-arm-controller", n: "Robot Arm Controller", p: "Controls & Robotics", t: "Kinematics + control", steps: ["forward-kinematics", "inverse-kinematics", "pid-control"] },
  { s: "drone-autopilot", n: "Drone Autopilot", p: "Controls & Robotics", t: "Dynamics, PID, estimation", steps: ["quadcopter", "pid-control", "kalman-filter", "rrt"] },
  { s: "mobile-robot-nav", n: "Mobile Robot Navigation", p: "Controls & Robotics", t: "Drive, plan, estimate", steps: ["differential-drive", "rrt", "kalman-filter"] },
  { s: "cart-pole-control", n: "Cart-Pole Control Design", p: "Controls & Robotics", t: "Balance & robustness", steps: ["cart-pole", "pid-control"] },
  { s: "servo-tuning-kit", n: "Servo Tuning Kit", p: "Controls & Robotics", t: "Motor, PID, Bode", steps: ["dc-motor", "pid-control", "bode-plot"] },
  { s: "dsp-pipeline", n: "DSP Pipeline", p: "Controls & Robotics", t: "Sample, FFT, filter", steps: ["aliasing", "fft", "filter-designer"] },
  { s: "state-estimator", n: "State Estimator", p: "Controls & Robotics", t: "Sensor fusion", steps: ["kalman-filter"] },
  { s: "motion-profile-generator", n: "Motion Profile Generator", p: "Controls & Robotics", t: "Kinematics to torque", steps: ["forward-kinematics", "dc-motor"] },
  { s: "vibration-control", n: "Vibration Control", p: "Controls & Robotics", t: "Modes & active control", steps: ["standing-waves", "pid-control"] },
  { s: "line-follower-robot", n: "Line-Follower Robot", p: "Controls & Robotics", t: "Sensor, PID, drive", steps: ["pid-control", "differential-drive"] },
  // ---- Data & Statistics (71-90) ----
  { s: "ml-model-trainer", n: "ML Model Trainer", p: "Data & Statistics", t: "Train, cluster, reduce", steps: ["neural-net", "kmeans", "pca", "gradient-descent"] },
  { s: "classification-pipeline", n: "Classification Pipeline", p: "Data & Statistics", t: "Reduce then classify", steps: ["pca", "neural-net"] },
  { s: "clustering-workbench", n: "Clustering Workbench", p: "Data & Statistics", t: "k-means & PCA", steps: ["kmeans", "pca"] },
  { s: "feature-engineering", n: "Feature Engineering", p: "Data & Statistics", t: "PCA & selection", steps: ["pca", "linear-regression"] },
  { s: "deep-net-playground", n: "Deep Net Playground", p: "Data & Statistics", t: "Backprop & overfitting", steps: ["neural-net", "gradient-descent"] },
  { s: "recommender-system", n: "Recommender System", p: "Data & Statistics", t: "Similarity & ranking", steps: ["pagerank", "kmeans"] },
  { s: "anomaly-detection", n: "Anomaly Detection", p: "Data & Statistics", t: "Distribution & threshold", steps: ["distributions", "kmeans"] },
  { s: "time-series-forecaster", n: "Time-Series Forecaster", p: "Data & Statistics", t: "Regress, Fourier, Kalman", steps: ["linear-regression", "fourier", "kalman-filter", "monte-carlo"] },
  { s: "nlp-basics-kit", n: "NLP Basics Kit", p: "Data & Statistics", t: "Embed & classify", steps: ["kmeans", "neural-net"] },
  { s: "image-processing-chain", n: "Image Processing Chain", p: "Data & Statistics", t: "Convolve & transform", steps: ["convolution", "fft"] },
  { s: "regression-workbench", n: "Regression Workbench", p: "Data & Statistics", t: "Fit, test, bootstrap", steps: ["linear-regression", "hypothesis-test", "confidence-interval", "bootstrap"] },
  { s: "ab-test-suite", n: "A/B Test Suite", p: "Data & Statistics", t: "Power & significance", steps: ["ab-test", "central-limit", "confidence-interval"] },
  { s: "bayesian-workbench", n: "Bayesian Workbench", p: "Data & Statistics", t: "Prior to posterior", steps: ["bayes-inference", "monte-carlo", "bootstrap"] },
  { s: "survey-analysis", n: "Survey Analysis", p: "Data & Statistics", t: "Sampling & intervals", steps: ["confidence-interval", "distributions"] },
  { s: "quality-control-spc", n: "Quality Control (SPC)", p: "Data & Statistics", t: "Chart & capability", steps: ["control-chart", "process-capability", "hypothesis-test"] },
  { s: "doe-optimizer", n: "DOE Optimizer", p: "Data & Statistics", t: "Design & response", steps: ["linear-regression", "hypothesis-test"] },
  { s: "meta-analysis", n: "Meta-Analysis", p: "Data & Statistics", t: "Effect & heterogeneity", steps: ["confidence-interval", "bootstrap"] },
  { s: "reliability-analysis", n: "Reliability Analysis", p: "Data & Statistics", t: "Weibull & MTBF", steps: ["distributions", "fatigue"] },
  { s: "bootstrap-uncertainty", n: "Bootstrap Uncertainty", p: "Data & Statistics", t: "Resampling CI", steps: ["bootstrap", "confidence-interval"] },
  { s: "causal-inference", n: "Causal Inference", p: "Data & Statistics", t: "Confounders & effect", steps: ["linear-regression", "hypothesis-test"] },
  // ---- Finance & Quant (91-110) ----
  { s: "portfolio-builder", n: "Portfolio Builder", p: "Finance & Quant", t: "Frontier, MC, VaR", steps: ["efficient-frontier", "monte-carlo", "value-at-risk"] },
  { s: "retirement-planner", n: "Retirement Planner", p: "Finance & Quant", t: "Growth & drawdown", steps: ["compound-interest", "monte-carlo", "amortization"] },
  { s: "mortgage-optimizer", n: "Mortgage Optimizer", p: "Finance & Quant", t: "Amortize & refinance", steps: ["amortization", "compound-interest"] },
  { s: "fixed-income-suite", n: "Fixed-Income Suite", p: "Finance & Quant", t: "Price, duration, risk", steps: ["bond-pricing", "value-at-risk"] },
  { s: "dividend-growth-model", n: "Dividend Growth Model", p: "Finance & Quant", t: "Discount & value", steps: ["compound-interest", "bond-pricing"] },
  { s: "rebalancing-strategy", n: "Rebalancing Strategy", p: "Finance & Quant", t: "Drift & cost", steps: ["efficient-frontier", "monte-carlo"] },
  { s: "college-savings", n: "College Savings", p: "Finance & Quant", t: "Growth to target", steps: ["compound-interest", "monte-carlo"] },
  { s: "emergency-fund-planner", n: "Emergency Fund Planner", p: "Finance & Quant", t: "Risk & target", steps: ["compound-interest", "monte-carlo"] },
  { s: "real-estate-analyzer", n: "Real-Estate Analyzer", p: "Finance & Quant", t: "Cash flow & IRR", steps: ["amortization", "compound-interest"] },
  { s: "fire-calculator", n: "FIRE Calculator", p: "Finance & Quant", t: "Savings to freedom", steps: ["compound-interest", "monte-carlo"] },
  { s: "options-desk", n: "Options Desk", p: "Finance & Quant", t: "Price, Greeks, payoff", steps: ["black-scholes", "option-payoff", "monte-carlo"] },
  { s: "volatility-surface", n: "Volatility Surface", p: "Finance & Quant", t: "Smile & calibration", steps: ["black-scholes", "monte-carlo"] },
  { s: "risk-dashboard", n: "Risk Dashboard", p: "Finance & Quant", t: "VaR & stress", steps: ["value-at-risk", "monte-carlo"] },
  { s: "delta-hedging-sim", n: "Delta Hedging Sim", p: "Finance & Quant", t: "Greeks & P&L", steps: ["black-scholes", "option-payoff"] },
  { s: "pairs-trading", n: "Pairs Trading", p: "Finance & Quant", t: "Cointegration & signal", steps: ["linear-regression", "monte-carlo"] },
  { s: "factor-model", n: "Factor Model", p: "Finance & Quant", t: "Exposures & attribution", steps: ["linear-regression", "pca"] },
  { s: "credit-risk", n: "Credit Risk", p: "Finance & Quant", t: "Default & loss", steps: ["monte-carlo", "value-at-risk"] },
  { s: "monte-carlo-pricer", n: "Monte Carlo Pricer", p: "Finance & Quant", t: "Paths & payoff", steps: ["monte-carlo", "black-scholes"] },
  { s: "yield-curve-trading", n: "Yield-Curve Trading", p: "Finance & Quant", t: "Duration & carry", steps: ["bond-pricing"] },
  { s: "backtester", n: "Backtester", p: "Finance & Quant", t: "Signal, Sharpe, drawdown", steps: ["monte-carlo", "value-at-risk"] },
  // ---- Physics & Quantum (111-130) ----
  { s: "orbital-mechanics-lab", n: "Orbital Mechanics Lab", p: "Physics & Quantum", t: "Kepler to N-body", steps: ["kepler", "orbital-transfer", "escape-velocity", "lagrange-points"] },
  { s: "projectile-range-kit", n: "Projectile Range Kit", p: "Physics & Quantum", t: "Drag & optimization", steps: ["projectile"] },
  { s: "pendulum-lab", n: "Pendulum Lab", p: "Physics & Quantum", t: "Simple to chaotic", steps: ["double-pendulum", "standing-waves"] },
  { s: "collision-analyzer", n: "Collision Analyzer", p: "Physics & Quantum", t: "Momentum & energy", steps: ["collisions"] },
  { s: "rotational-dynamics", n: "Rotational Dynamics", p: "Physics & Quantum", t: "Torque & precession", steps: ["collisions", "double-pendulum"] },
  { s: "spring-mass-systems", n: "Spring-Mass Systems", p: "Physics & Quantum", t: "Modes & resonance", steps: ["cloth", "standing-waves"] },
  { s: "rocket-flight", n: "Rocket Flight", p: "Physics & Quantum", t: "Staging to orbit", steps: ["rocket", "rocket-staging", "standard-atmosphere"] },
  { s: "fluid-statics-kit", n: "Fluid Statics Kit", p: "Physics & Quantum", t: "Buoyancy & stability", steps: ["buoyancy"] },
  { s: "wave-lab", n: "Wave Lab", p: "Physics & Quantum", t: "Interference to FFT", steps: ["wave-interference", "standing-waves", "doppler", "beats", "fft"] },
  { s: "chaos-explorer", n: "Chaos Explorer", p: "Physics & Quantum", t: "Pendulum to bifurcation", steps: ["double-pendulum", "attractors", "bifurcation"] },
  { s: "quantum-sandbox", n: "Quantum Sandbox", p: "Physics & Quantum", t: "Box, tunnel, orbitals", steps: ["particle-box", "quantum-tunneling", "quantum-harmonic", "hydrogen-orbitals"] },
  { s: "optics-bench", n: "Optics Bench", p: "Physics & Quantum", t: "Lenses to diffraction", steps: ["ray-optics", "diffraction-grating", "wave-interference", "prism"] },
  { s: "laser-cavity-lab", n: "Laser Cavity Lab", p: "Physics & Quantum", t: "Gain, mirror, beam", steps: ["laser-cavity", "bragg-mirror", "gaussian-beam"] },
  { s: "spectroscopy-kit", n: "Spectroscopy Kit", p: "Physics & Quantum", t: "Levels & lines", steps: ["blackbody", "hydrogen-orbitals"] },
  { s: "relativity-lab", n: "Relativity Lab", p: "Physics & Quantum", t: "Dilation & Doppler", steps: ["special-relativity", "doppler"] },
  { s: "qubit-playground", n: "Qubit Playground", p: "Physics & Quantum", t: "Bloch & measurement", steps: ["bloch-sphere", "stern-gerlach"] },
  { s: "photovoltaic-physics", n: "Photovoltaic Physics", p: "Physics & Quantum", t: "Band gap to yield", steps: ["led", "solar-panel"] },
  { s: "blackbody-radiation-lab", n: "Blackbody & Radiation", p: "Physics & Quantum", t: "Planck & color", steps: ["blackbody"] },
  { s: "interferometer", n: "Interferometer", p: "Physics & Quantum", t: "Fringes & coherence", steps: ["wave-interference", "double-slit", "single-slit"] },
  { s: "nuclear-decay-chain", n: "Nuclear Decay Chain", p: "Physics & Quantum", t: "Half-life to dose", steps: ["radioactive-decay", "radiometric-dating", "radiation-dose"] },
  // ---- Chemistry & Materials (131-150) ----
  { s: "reaction-engineering-kit", n: "Reaction Engineering Kit", p: "Chemistry & Materials", t: "Kinetics to titration", steps: ["reaction-kinetics", "equilibrium", "titration"] },
  { s: "reactor-designer", n: "Reactor Designer", p: "Chemistry & Materials", t: "Conversion & heat", steps: ["reaction-kinetics", "equilibrium"] },
  { s: "distillation-column", n: "Distillation Column", p: "Chemistry & Materials", t: "VLE & stages", steps: ["equilibrium", "ideal-gas"] },
  { s: "ph-buffer-lab", n: "pH & Buffer Lab", p: "Chemistry & Materials", t: "Titration & buffer", steps: ["ph", "titration"] },
  { s: "electrochem-cell", n: "Electrochem Cell", p: "Chemistry & Materials", t: "Nernst & kinetics", steps: ["ph", "reaction-kinetics"] },
  { s: "combustion-analyzer", n: "Combustion Analyzer", p: "Chemistry & Materials", t: "Stoichiometry & flame", steps: ["ideal-gas", "maxwell-boltzmann"] },
  { s: "gas-process-kit", n: "Gas Process Kit", p: "Chemistry & Materials", t: "Compression & liquefaction", steps: ["ideal-gas", "maxwell-boltzmann", "gas"] },
  { s: "polymerization", n: "Polymerization", p: "Chemistry & Materials", t: "Chain & properties", steps: ["reaction-kinetics"] },
  { s: "crystallization", n: "Crystallization", p: "Chemistry & Materials", t: "Nucleation & yield", steps: ["equilibrium", "phase-diagram"] },
  { s: "membrane-separation", n: "Membrane Separation", p: "Chemistry & Materials", t: "Diffusion & flux", steps: ["random-walk"] },
  { s: "materials-selector", n: "Materials Selector", p: "Chemistry & Materials", t: "Strength to fatigue", steps: ["stress-strain", "mohrs-circle", "fatigue", "thermal-expansion"] },
  { s: "heat-treatment", n: "Heat Treatment", p: "Chemistry & Materials", t: "Cooling & hardness", steps: ["phase-diagram", "heat-3d"] },
  { s: "composite-designer", n: "Composite Designer", p: "Chemistry & Materials", t: "Stiffness & failure", steps: ["stress-strain", "mohrs-circle"] },
  { s: "fatigue-life-predictor", n: "Fatigue Life Predictor", p: "Chemistry & Materials", t: "S-N to life", steps: ["fatigue", "stress-strain"] },
  { s: "casting-solidification", n: "Casting & Solidification", p: "Chemistry & Materials", t: "Heat & shrinkage", steps: ["heat-3d", "phase-diagram"] },
  { s: "3d-printing-optimizer", n: "3D Printing Optimizer", p: "Chemistry & Materials", t: "Warping & strength", steps: ["thermal-expansion", "stress-strain"] },
  { s: "machining-parameters", n: "Machining Parameters", p: "Chemistry & Materials", t: "Force & tool life", steps: ["cnc-feeds-speeds"] },
  { s: "weld-design", n: "Weld Design", p: "Chemistry & Materials", t: "Heat & residual stress", steps: ["thermal-expansion", "stress-strain"] },
  { s: "corrosion-rate", n: "Corrosion Rate", p: "Chemistry & Materials", t: "Electrochem & life", steps: ["reaction-kinetics"] },
  { s: "fracture-mechanics", n: "Fracture Mechanics", p: "Chemistry & Materials", t: "Toughness & crack", steps: ["stress-strain", "fatigue"] },
  // ---- Earth & First Responders (151-170) ----
  { s: "climate-scenario-model", n: "Climate Scenario Model", p: "Earth & First Responders", t: "Energy to feedback", steps: ["energy-balance", "carbon-cycle", "milankovitch", "daisyworld"] },
  { s: "watershed-flood-kit", n: "Watershed & Flood Kit", p: "Earth & First Responders", t: "Runoff & routing", steps: ["groundwater", "spatial-interpolation"] },
  { s: "air-quality-model", n: "Air Quality Model", p: "Earth & First Responders", t: "Emission to exposure", steps: ["hazmat-plume", "spatial-interpolation"] },
  { s: "coastal-erosion", n: "Coastal Erosion", p: "Earth & First Responders", t: "Waves & sediment", steps: ["tsunami", "spatial-interpolation"] },
  { s: "groundwater-contamination", n: "Groundwater Contamination", p: "Earth & First Responders", t: "Flow & remediation", steps: ["groundwater", "spatial-interpolation"] },
  { s: "solar-wind-site", n: "Solar & Wind Site", p: "Earth & First Responders", t: "Yield & capacity", steps: ["solar-panel", "wind-power"] },
  { s: "wildfire-risk-map", n: "Wildfire Risk Map", p: "Earth & First Responders", t: "Fuel, weather, spread", steps: ["fire-spread", "atmospheric-stability"] },
  { s: "glacier-mass-balance", n: "Glacier Mass Balance", p: "Earth & First Responders", t: "Melt & retreat", steps: ["milankovitch", "energy-balance"] },
  { s: "river-meander", n: "River Meander", p: "Earth & First Responders", t: "Erosion & migration", steps: ["groundwater"] },
  { s: "carbon-footprint-suite", n: "Carbon Footprint Suite", p: "Earth & First Responders", t: "Emissions & offset", steps: ["carbon-footprint", "carbon-cycle"] },
  { s: "wildfire-response-planner", n: "Wildfire Response Planner", p: "Earth & First Responders", t: "Spread to evacuation", steps: ["fire-spread", "hazmat-plume", "evacuation", "radio-range"] },
  { s: "hazmat-incident-kit", n: "Hazmat Incident Kit", p: "Earth & First Responders", t: "Plume to triage", steps: ["hazmat-plume", "triage"] },
  { s: "structural-collapse", n: "Structural Collapse", p: "Earth & First Responders", t: "Load & search grid", steps: ["base-shear", "beam-deflection"] },
  { s: "flood-evacuation", n: "Flood Evacuation", p: "Earth & First Responders", t: "Inundation & routing", steps: ["groundwater", "evacuation"] },
  { s: "active-shooter-response", n: "Active-Shooter Response", p: "Earth & First Responders", t: "Egress & staging", steps: ["evacuation"] },
  { s: "mass-casualty-triage", n: "Mass-Casualty Triage", p: "Earth & First Responders", t: "Triage to capacity", steps: ["triage", "sir-model"] },
  { s: "fireground-hydraulics", n: "Fireground Hydraulics", p: "Earth & First Responders", t: "Hose to pump", steps: ["hose-flow"] },
  { s: "search-rescue-grid", n: "Search & Rescue Grid", p: "Earth & First Responders", t: "Probability & coverage", steps: ["viewshed", "spatial-interpolation"] },
  { s: "bomb-standoff-planner", n: "Bomb Standoff Planner", p: "Earth & First Responders", t: "Overpressure & cordon", steps: ["blast-standoff"] },
  { s: "pandemic-response", n: "Pandemic Response", p: "Earth & First Responders", t: "Spread to capacity", steps: ["sir-model", "epidemic-network", "triage"] },
  // ---- Biology & Aerospace (171-190) ----
  { s: "epidemic-response-model", n: "Epidemic Response Model", p: "Biology & Aerospace", t: "SIR to triage", steps: ["sir-model", "epidemic-network", "evacuation", "triage"] },
  { s: "pharmacokinetics-suite", n: "Pharmacokinetics Suite", p: "Biology & Aerospace", t: "Dosing & clearance", steps: ["radioactive-decay", "monte-carlo"] },
  { s: "neuroscience-lab", n: "Neuroscience Lab", p: "Biology & Aerospace", t: "Spikes to FFT", steps: ["neuron", "fft"] },
  { s: "population-ecology-lab", n: "Population Ecology Lab", p: "Biology & Aerospace", t: "Predator-prey to drift", steps: ["lotka-volterra", "logistic-growth", "genetic-drift", "hardy-weinberg"] },
  { s: "tumor-growth", n: "Tumor Growth", p: "Biology & Aerospace", t: "Proliferation & dose", steps: ["logistic-growth", "reaction-diffusion"] },
  { s: "cardiac-rhythm", n: "Cardiac Rhythm", p: "Biology & Aerospace", t: "Conduction & arrhythmia", steps: ["neuron"] },
  { s: "vaccine-strategy", n: "Vaccine Strategy", p: "Biology & Aerospace", t: "Herd immunity & rollout", steps: ["sir-model", "epidemic-network"] },
  { s: "enzyme-pathway", n: "Enzyme Pathway", p: "Biology & Aerospace", t: "Kinetics & flux", steps: ["enzyme-kinetics"] },
  { s: "genetics-lab", n: "Genetics Lab", p: "Biology & Aerospace", t: "Selection & drift", steps: ["hardy-weinberg", "genetic-drift"] },
  { s: "blood-flow", n: "Blood Flow", p: "Biology & Aerospace", t: "Vessel & shear", steps: ["fluid"] },
  { s: "mission-planner", n: "Mission Planner", p: "Biology & Aerospace", t: "Staging to Lagrange", steps: ["rocket-staging", "escape-velocity", "orbital-transfer", "lagrange-points"] },
  { s: "satellite-orbit", n: "Satellite Orbit", p: "Biology & Aerospace", t: "Elements & ground track", steps: ["orbital-elements", "kepler"] },
  { s: "exoplanet-detective", n: "Exoplanet Detective", p: "Biology & Aerospace", t: "Transit to mass", steps: ["exoplanet-transit", "hr-diagram"] },
  { s: "telescope-designer", n: "Telescope Designer", p: "Biology & Aerospace", t: "Aperture to resolution", steps: ["telescope"] },
  { s: "reentry-analysis", n: "Reentry Analysis", p: "Biology & Aerospace", t: "Trajectory & heating", steps: ["reentry", "standard-atmosphere"] },
  { s: "interplanetary-transfer", n: "Interplanetary Transfer", p: "Biology & Aerospace", t: "Window & delta-v", steps: ["orbital-transfer", "escape-velocity"] },
  { s: "star-lifecycle", n: "Star Lifecycle", p: "Biology & Aerospace", t: "H-R to fate", steps: ["hr-diagram", "blackbody"] },
  { s: "gravitational-lensing", n: "Gravitational Lensing", p: "Biology & Aerospace", t: "Mass & deflection", steps: ["gravity-well"] },
  { s: "launch-vehicle-sizing", n: "Launch Vehicle Sizing", p: "Biology & Aerospace", t: "Payload & staging", steps: ["rocket-staging", "standard-atmosphere"] },
  { s: "space-debris-tracker", n: "Space Debris Tracker", p: "Biology & Aerospace", t: "Orbit & conjunction", steps: ["orbital-elements", "kepler"] },
  // ---- Operations & Economics (191-200) ----
  { s: "supply-chain-optimizer", n: "Supply-Chain Optimizer", p: "Operations & Economics", t: "EOQ to network flow", steps: ["eoq", "queueing", "linear-programming", "max-flow"] },
  { s: "facility-location", n: "Facility Location", p: "Operations & Economics", t: "Demand & cost", steps: ["shortest-path", "linear-programming"] },
  { s: "project-portfolio", n: "Project Portfolio", p: "Operations & Economics", t: "Critical path & risk", steps: ["critical-path", "monte-carlo"] },
  { s: "market-equilibrium-lab", n: "Market Equilibrium Lab", p: "Operations & Economics", t: "Supply, demand, tax", steps: ["supply-demand", "elasticity", "laffer-curve"] },
  { s: "auction-designer", n: "Auction Designer", p: "Operations & Economics", t: "Mechanism & revenue", steps: ["game-theory"] },
  { s: "pricing-strategy", n: "Pricing Strategy", p: "Operations & Economics", t: "Elasticity & margin", steps: ["elasticity", "monopoly"] },
  { s: "network-reliability", n: "Network Reliability", p: "Operations & Economics", t: "Max-flow & redundancy", steps: ["max-flow", "centrality"] },
  { s: "traffic-flow-planner", n: "Traffic Flow Planner", p: "Operations & Economics", t: "Flow & signal timing", steps: ["traffic", "shortest-path"] },
  { s: "inventory-demand", n: "Inventory & Demand", p: "Operations & Economics", t: "Forecast & safety stock", steps: ["eoq", "monte-carlo"] },
  { s: "game-theoretic-strategy", n: "Game-Theoretic Strategy", p: "Operations & Economics", t: "Nash & evolution", steps: ["game-theory"] },
];

export const multiBySlug = (slug: string) => MULTIS.find((m) => m.s === slug);
