import type { Metadata } from "next";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { Disclaimer } from "@/components/Disclaimer";
import { JsonLd } from "@/components/JsonLd";
import { softwareAppLd } from "@/lib/seo";
import { ProductGrid } from "@/components/ProductCard";
import { contextualProducts } from "@/lib/products";
import { StudioBrowser } from "@/components/studio/StudioBrowser";

export const metadata: Metadata = {
  title: "PolySim Studio — Run Real Simulations in Your Browser",
  description:
    "Launch live, browser-native simulations: particle/N-body physics, 2D fluid dynamics (CFD), dynamical systems, symbolic math, and an AI surrogate model. Free, no install.",
  alternates: { canonical: "/studio" },
};

export const SIMS = [
  { slug: "graph", name: "Visual Node Graph", desc: "Wire blocks into a live dataflow — the real editor. Symbolic calculus built in.", tag: "Flagship" },
  { slug: "particles", name: "Particle / N-Body", desc: "Gravity, orbits, and impulse collisions with a real symplectic integrator.", tag: "Physics" },
  { slug: "fluid", name: "2D Fluid (CFD)", desc: "Interactive incompressible Navier–Stokes via Stam's stable-fluids method.", tag: "Engineering" },
  { slug: "dynamics", name: "Dynamical Systems", desc: "Lorenz, SIR epidemics, pendulums, predator–prey, and reaction–diffusion.", tag: "Math / Bio" },
  { slug: "fields", name: "Heat & Wave Fields", desc: "2D heat diffusion and the 1D wave equation, solved live.", tag: "PDE" },
  { slug: "cas", name: "Symbolic Math", desc: "Parse, differentiate, simplify, solve, and plot — a real CAS in your browser.", tag: "Math" },
  { slug: "surrogate", name: "AI Surrogate", desc: "Train an ML surrogate on our solver for instant predictions. The PhysicsX play.", tag: "AI" },
  { slug: "gpu", name: "GPU Compute (WebGPU)", desc: "Hundreds of thousands of particles on your GPU via WGSL shaders.", tag: "WebGPU" },
  { slug: "gpu-fluid", name: "WebGPU Fluid", desc: "High-res GPU smoke advection you can stir.", tag: "WebGPU" },
  { slug: "gpu-nbody", name: "GPU N-Body", desc: "Thousands of bodies, full O(n²) gravity on the GPU.", tag: "WebGPU" },
  { slug: "gpu-pde", name: "GPU PDE Solver", desc: "Steady heat/Poisson via GPU Jacobi at high res.", tag: "WebGPU" },
  { slug: "gpu-fluid-3d", name: "GPU 3D Fluid", desc: "3D smoke, simulated + raymarched on the GPU.", tag: "WebGPU" },
  { slug: "gpu-nbody-pm", name: "Particle-Mesh N-Body", desc: "100k+ bodies via GPU particle-mesh gravity.", tag: "WebGPU" },
  { slug: "cfd-3d", name: "3D CFD", desc: "3D Navier–Stokes plume with z-slices.", tag: "3D Engineering" },
  { slug: "3d", name: "3D N-Body", desc: "Gravitation in 3D with a drag-to-orbit camera.", tag: "3D Physics" },
  { slug: "fea-3d", name: "3D FEA Space Frame", desc: "3D structural analysis; orbit the deformed tower.", tag: "3D Engineering" },
  { slug: "heat-3d", name: "3D Heat Diffusion", desc: "Volumetric heat with slices and orbit view.", tag: "3D PDE" },
  { slug: "fea", name: "FEA Truss", desc: "Finite-element structural analysis: forces & deflection.", tag: "Engineering" },
  { slug: "electromagnetics", name: "Electrostatics", desc: "Charges, potential heatmaps, and field lines.", tag: "Physics" },
  { slug: "molecular-dynamics", name: "Molecular Dynamics", desc: "Lennard-Jones atoms; melt a lattice.", tag: "Chemistry" },
  { slug: "mesh", name: "Meshing + BCs", desc: "Paint boundary conditions; solve steady heat.", tag: "Engineering" },
  { slug: "vector-field", name: "Vector Fields", desc: "Plot any F(x,y) as a live quiver diagram.", tag: "Math" },
  { slug: "optimize", name: "Optimize + UQ", desc: "Gradient descent and Monte-Carlo uncertainty.", tag: "Data" },
  { slug: "svd", name: "SVD", desc: "Compress a 64×64 image with a real Jacobi SVD — trade rank k for size, live.", tag: "Linear Algebra" },
  { slug: "linear-transform", name: "Linear Transformation", desc: "Warp the plane with a 2×2 matrix: live determinant, eigenvectors, and unit-square area.", tag: "Linear Algebra" },
  { slug: "matrix-elimination", name: "Gaussian Elimination", desc: "Step through LU decomposition with partial pivoting — pivots, row swaps, L, U, and det.", tag: "Linear Algebra" },
  { slug: "least-squares", name: "Least Squares", desc: "Drag points and fit a polynomial by least squares — residuals, R², RMSE, overfitting.", tag: "Linear Algebra" },
  { slug: "root-finding", name: "Root Finding", desc: "Solve f(x)=0 with Newton, bisection, and secant — tangents, brackets, chords animated.", tag: "Numerical Methods" },
  { slug: "numerical-integration", name: "Numerical Integration", desc: "Estimate a definite integral with Riemann, trapezoid & Simpson rules; watch the error shrink.", tag: "Numerical Methods" },
  { slug: "ode-methods", name: "ODE Solver Methods", desc: "Compare Euler, Heun, and RK4 integrating an ODE against its exact analytic solution.", tag: "Numerical Methods" },
  { slug: "curve-fitting", name: "Curve Fitting", desc: "Fit exponential, logistic, Gaussian, power & sinusoid models to noisy data via Gauss–Newton.", tag: "Numerical Methods" },
  { slug: "image-convolution", name: "Image Convolution", desc: "Apply 3×3 kernels — blur, sharpen, Laplacian edge, emboss, Sobel — to a live test image.", tag: "Image Processing" },
  { slug: "edge-detection", name: "Edge Detection", desc: "Sobel, Prewitt, and full Canny edge detection on a test image — live in your browser.", tag: "Image Processing" },
  { slug: "morphology", name: "Morphology", desc: "Erosion, dilation, opening & closing on a binary image with a chosen structuring element.", tag: "Image Processing" },
  { slug: "image-fft", name: "2D Image FFT", desc: "2D Fourier transform of an image with live low/high/band-pass frequency filtering.", tag: "Image Processing" },
  { slug: "histogram-equalization", name: "Histogram Equalization", desc: "Equalize, stretch, or gamma-correct a low-contrast image using its intensity CDF.", tag: "Image Processing" },
  { slug: "thresholding", name: "Image Thresholding", desc: "Global, Otsu, and adaptive local thresholding with a live histogram and foreground %.", tag: "Image Processing" },
  { slug: "spectrogram", name: "Spectrogram", desc: "Real STFT spectrogram in-browser: chirps, tones, and hops as a time–frequency heatmap.", tag: "Signal Processing" },
  { slug: "z-transform", name: "Z-Transform", desc: "Drag poles & zeros on the z-plane; see live magnitude, phase & impulse response.", tag: "Signal Processing" },
  { slug: "wavelet", name: "Wavelet Transform", desc: "Real Haar/db4 DWT: multi-level decomposition, live scalogram, and threshold denoising.", tag: "Signal Processing" },
  { slug: "lqr", name: "LQR Control", desc: "Solve the Riccati equation to balance a cart-pole with an optimal LQR controller.", tag: "Control Systems" },
  { slug: "state-observer", name: "State Observer", desc: "Reconstruct hidden state from a single output via a Luenberger observer.", tag: "Control Systems" },
  { slug: "digital-modulation", name: "Digital Modulation", desc: "Modulate bits with QAM/PSK/FSK, add AWGN, and watch the constellation and BER live.", tag: "Communications" },
  { slug: "eye-diagram", name: "Eye Diagram", desc: "Pulse-shape NRZ/raised-cosine bits; add noise & jitter and watch ISI open or close the eye.", tag: "Communications" },
  { slug: "ber-snr", name: "BER vs SNR", desc: "Waterfall BER vs Eb/N0 for BPSK/QPSK, 16/64-QAM & BFSK — theory + AWGN Monte-Carlo.", tag: "Communications" },
  { slug: "gaussian-process", name: "Gaussian Process", desc: "Interactive 1D GP regression with live posterior mean, 95% uncertainty band, and samples.", tag: "Machine Learning" },
  { slug: "block-diagram", name: "Block Diagram Simulator", desc: "Wire block diagrams and run them with RK4 in your browser — a free Simulink alternative.", tag: "Control Systems" },
  { slug: "hardware-bridge", name: "Hardware Bridge", desc: "Connect a real Arduino/sensor/motor over WebSerial — live data in your browser, no install.", tag: "Hardware" },
  { slug: "controller-code", name: "Controller → Code", desc: "Tune a PID, preview the closed loop, and export a ready-to-flash Arduino/C/Python sketch.", tag: "Hardware" },
  { slug: "fabricate", name: "Fabricate", desc: "Design a plate/bracket and export exact DXF, STL, and a bill of materials — make it real.", tag: "Fabrication" },
  { slug: "model-fit", name: "Model Fit & Validate", desc: "Paste real measured data and fit a validated model (R², residuals) — identify your system.", tag: "Machine Learning" },
  { slug: "notebook", name: "Notebook", desc: "Cells of prose + symbolic math + compute.", tag: "Math" },
  { slug: "double-pendulum", name: "Double Pendulum", desc: "The textbook chaotic system, integrated with RK4.", tag: "Physics" },
  { slug: "projectile", name: "Projectile Motion", desc: "Ballistics with air drag; tune angle and speed.", tag: "Physics" },
  { slug: "ising", name: "Ising Model", desc: "A live magnetic phase transition via Monte Carlo.", tag: "Physics" },
  { slug: "fractals", name: "Fractal Explorer", desc: "Zoom into the Mandelbrot and Julia sets.", tag: "Math" },
  { slug: "fourier", name: "Fourier Series", desc: "Build waves from sine harmonics.", tag: "Math" },
  { slug: "grapher", name: "Function Grapher", desc: "Plot up to three functions at once.", tag: "Math" },
  { slug: "surface-3d", name: "3D Surface Plotter", desc: "Orbit any z = f(x, y) surface.", tag: "Math" },
  { slug: "matrix", name: "Matrix Calculator", desc: "Multiply, invert, determinant, transpose.", tag: "Math" },
  { slug: "attractors", name: "Strange Attractors", desc: "Lorenz, Rössler, Aizawa & more in 3D.", tag: "Physics" },
  { slug: "rlc", name: "RLC Circuit", desc: "Step response and damping regimes.", tag: "Engineering" },
  { slug: "wave-interference", name: "Wave Interference", desc: "Two-source ripple-tank fringes.", tag: "Physics" },
  { slug: "cellular-automata", name: "Cellular Automata", desc: "Wolfram rules & Conway's Life.", tag: "CS / Math" },
  { slug: "random-walk", name: "Random Walk", desc: "Brownian motion and diffusion.", tag: "Physics" },
  { slug: "taylor", name: "Taylor Series", desc: "Polynomial approximation, live.", tag: "Math" },
  { slug: "newton", name: "Newton's Method", desc: "Root finding, tangent by tangent.", tag: "Math" },
  { slug: "distributions", name: "Distributions", desc: "Normal, Poisson, binomial & more.", tag: "Math" },
  { slug: "kepler", name: "Kepler Orbits", desc: "Conic-section orbits under gravity.", tag: "Physics" },
  { slug: "double-slit", name: "Double-Slit", desc: "Quantum interference + diffraction.", tag: "Physics" },
  { slug: "cloth", name: "Cloth / Spring-Mass", desc: "Verlet cloth you can grab and swing.", tag: "Physics" },
  { slug: "gravity-well", name: "Gravity Well", desc: "Curved-spacetime rubber sheet + orbit.", tag: "Physics" },
  { slug: "epidemic-network", name: "Epidemic Network", desc: "Agent-based SIR on a contact graph.", tag: "Bio" },
  { slug: "gradient-descent", name: "Gradient Descent", desc: "Optimization on loss landscapes.", tag: "Data / ML" },
  { slug: "complex", name: "Complex Functions", desc: "Domain coloring of f(z).", tag: "Math" },
  { slug: "sorting", name: "Sorting Visualizer", desc: "Watch algorithms sort in real time.", tag: "CS" },
  { slug: "boids", name: "Boids Flocking", desc: "Emergent flocking from three rules.", tag: "Emergence" },
  { slug: "traffic", name: "Traffic Flow", desc: "Phantom jams from random braking.", tag: "Complex Systems" },
  { slug: "predator-prey", name: "Spatial Predator–Prey", desc: "Agent-based ecology with waves.", tag: "Bio" },
  { slug: "lissajous", name: "Lissajous Curves", desc: "Two sine waves, endless patterns.", tag: "Math" },
  { slug: "magnetic-pendulum", name: "Magnetic Pendulum", desc: "Fractal basins of attraction.", tag: "Physics" },
  { slug: "percolation", name: "Percolation", desc: "A phase transition in connectivity.", tag: "Physics" },
  { slug: "dla", name: "DLA Growth", desc: "Branching fractals from random walks.", tag: "Physics" },
  { slug: "ray-optics", name: "Ray Optics / Lenses", desc: "Trace rays through lenses.", tag: "Physics" },
  { slug: "gas", name: "Gas in a Box", desc: "Kinetic theory → pressure (PV=nRT).", tag: "Physics" },
  { slug: "collisions", name: "Elastic Collisions", desc: "Momentum & energy conservation.", tag: "Physics" },
  { slug: "buoyancy", name: "Buoyancy", desc: "Archimedes — float or sink by density.", tag: "Physics" },
  { slug: "rocket", name: "Rocket Equation", desc: "Tsiolkovsky Δv budget calculator.", tag: "Aerospace" },
  { slug: "blackbody", name: "Blackbody Radiation", desc: "Planck curve + Wien's law.", tag: "Physics" },
  { slug: "pendulum-wave", name: "Pendulum Wave", desc: "Phase art from many periods.", tag: "Physics" },
  { slug: "orbital-transfer", name: "Orbital Transfer", desc: "Hohmann transfer Δv.", tag: "Aerospace" },
  { slug: "standing-waves", name: "Standing Waves", desc: "Harmonics, nodes & antinodes.", tag: "Physics" },
  { slug: "doppler", name: "Doppler Effect", desc: "Moving-source wavefronts & sonic boom.", tag: "Physics" },
  { slug: "snells-law", name: "Snell's Law", desc: "Refraction & total internal reflection.", tag: "Optics" },
  { slug: "diffraction-grating", name: "Diffraction Grating", desc: "N-slit interference maxima.", tag: "Optics" },
  { slug: "beats", name: "Beats", desc: "Two close tones interfere.", tag: "Waves" },
  { slug: "mirror", name: "Curved Mirrors", desc: "Concave/convex ray tracing.", tag: "Optics" },
  { slug: "prism", name: "Prism Dispersion", desc: "White light into a spectrum.", tag: "Optics" },
  { slug: "fft", name: "Fourier Transform", desc: "Signal → frequency spectrum.", tag: "Signals" },
  { slug: "titration", name: "Titration Curve", desc: "pH vs base added; equivalence point.", tag: "Chemistry" },
  { slug: "reaction-kinetics", name: "Reaction Kinetics", desc: "Rate laws & Arrhenius decay.", tag: "Chemistry" },
  { slug: "equilibrium", name: "Chemical Equilibrium", desc: "Le Chatelier shifts.", tag: "Chemistry" },
  { slug: "ph", name: "pH Calculator", desc: "pH/pOH and the acid-base scale.", tag: "Chemistry" },
  { slug: "radioactive-decay", name: "Radioactive Decay", desc: "Half-life exponential decay.", tag: "Chemistry" },
  { slug: "maxwell-boltzmann", name: "Maxwell-Boltzmann", desc: "Molecular speed distribution.", tag: "Chemistry" },
  { slug: "ideal-gas", name: "Ideal Gas Law", desc: "PV = nRT with a live piston.", tag: "Chemistry" },
  { slug: "bifurcation", name: "Bifurcation Diagram", desc: "Logistic map route to chaos.", tag: "Math" },
  { slug: "direction-field", name: "Direction Field", desc: "Slope fields + solution curves.", tag: "Math" },
  { slug: "riemann", name: "Riemann Sums", desc: "Integrals as stacked rectangles.", tag: "Math" },
  { slug: "eigenvectors", name: "Eigenvectors", desc: "2×2 transforms & invariant directions.", tag: "Math" },
  { slug: "markov", name: "Markov Chains", desc: "Converge to a stationary distribution.", tag: "Math" },
  { slug: "parametric", name: "Parametric Grapher", desc: "Trace x(t), y(t) curves.", tag: "Math" },
  { slug: "numerical-methods", name: "Euler vs RK4", desc: "ODE integration accuracy.", tag: "Math" },
  { slug: "pathfinding", name: "A* Pathfinding", desc: "Shortest path, draw walls.", tag: "CS / AI" },
  { slug: "maze", name: "Maze Generator", desc: "Carve & solve perfect mazes.", tag: "CS / AI" },
  { slug: "neural-net", name: "Neural Network", desc: "Train an MLP, watch it learn.", tag: "CS / AI" },
  { slug: "kmeans", name: "k-Means Clustering", desc: "Unsupervised clustering, live.", tag: "CS / AI" },
  { slug: "convex-hull", name: "Convex Hull", desc: "Wrap points in O(n log n).", tag: "CS / AI" },
  { slug: "l-system", name: "L-System Fractals", desc: "Grow plants from grammars.", tag: "CS / AI" },
  { slug: "turing-machine", name: "Turing Machine", desc: "The model of computation.", tag: "CS / AI" },
  { slug: "convolution", name: "Image Convolution", desc: "Kernels behind every CNN.", tag: "CS / AI" },
  { slug: "forest-fire", name: "Forest Fire Model", desc: "Self-organized criticality.", tag: "Complex Systems" },
  { slug: "sandpile", name: "Abelian Sandpile", desc: "Avalanches build a fractal.", tag: "Complex Systems" },
  { slug: "schelling", name: "Schelling Segregation", desc: "Mild bias, sharp segregation.", tag: "Complex Systems" },
  { slug: "langtons-ant", name: "Langton's Ant", desc: "Two rules, emergent highway.", tag: "Complex Systems" },
  { slug: "reaction-diffusion", name: "Reaction-Diffusion", desc: "Gray-Scott Turing patterns.", tag: "Complex Systems" },
  { slug: "wolfram-ca", name: "Elementary CA", desc: "Wolfram's 256 rules.", tag: "Complex Systems" },
  { slug: "genetic-algorithm", name: "Genetic Algorithm", desc: "Evolve toward the peak.", tag: "Complex Systems" },
  { slug: "ant-colony", name: "Ant Colony Optimization", desc: "Swarm-solved TSP.", tag: "Complex Systems" },
  { slug: "fire-spread", name: "Wildfire Spread", desc: "Wind + slope fire behavior.", tag: "First Responders" },
  { slug: "hazmat-plume", name: "Hazmat Plume", desc: "Gaussian dispersion + PAD.", tag: "First Responders" },
  { slug: "evacuation", name: "Building Evacuation", desc: "Egress flow & clear time.", tag: "First Responders" },
  { slug: "triage", name: "START Triage", desc: "Mass-casualty triage tool.", tag: "First Responders" },
  { slug: "hose-flow", name: "Fire Hose Hydraulics", desc: "Friction loss & pump pressure.", tag: "First Responders" },
  { slug: "skid-to-stop", name: "Skid-to-Stop Speed", desc: "Accident reconstruction.", tag: "First Responders" },
  { slug: "radio-range", name: "Radio Range", desc: "VHF/UHF link budget.", tag: "First Responders" },
  { slug: "blast-standoff", name: "Blast Standoff", desc: "Overpressure & safe distance.", tag: "First Responders" },
  { slug: "exoplanet-transit", name: "Exoplanet Transit", desc: "Light-curve transit method.", tag: "Astronomy" },
  { slug: "hr-diagram", name: "H-R Diagram", desc: "The map of the stars.", tag: "Astronomy" },
  { slug: "lagrange-points", name: "Lagrange Points", desc: "Restricted 3-body equilibria.", tag: "Astronomy" },
  { slug: "roche-limit", name: "Roche Limit", desc: "When tides shred a moon.", tag: "Astronomy" },
  { slug: "hubble-law", name: "Hubble's Law", desc: "The expanding universe.", tag: "Astronomy" },
  { slug: "telescope", name: "Telescope Optics", desc: "Resolution & magnification.", tag: "Astronomy" },
  { slug: "parallax", name: "Stellar Parallax", desc: "Distance from angle shift.", tag: "Astronomy" },
  { slug: "escape-velocity", name: "Escape Velocity", desc: "Speed to leave a world.", tag: "Astronomy" },
  { slug: "energy-balance", name: "Energy Balance", desc: "Greenhouse equilibrium temp.", tag: "Earth & Climate" },
  { slug: "daisyworld", name: "Daisyworld", desc: "Planetary self-regulation.", tag: "Earth & Climate" },
  { slug: "milankovitch", name: "Milankovitch Cycles", desc: "Orbital forcing of ice ages.", tag: "Earth & Climate" },
  { slug: "tsunami", name: "Tsunami Propagation", desc: "Shallow-water wave shoaling.", tag: "Earth & Climate" },
  { slug: "carbon-cycle", name: "Carbon Cycle", desc: "Reservoir box model.", tag: "Earth & Climate" },
  { slug: "seismic", name: "Earthquake Shaking", desc: "Magnitude, energy, intensity.", tag: "Earth & Climate" },
  { slug: "groundwater", name: "Groundwater Drawdown", desc: "Well cone of depression.", tag: "Earth & Climate" },
  { slug: "lapse-rate", name: "Lapse Rate", desc: "Atmosphere & cloud base.", tag: "Earth & Climate" },
  { slug: "black-scholes", name: "Black-Scholes", desc: "Option pricing + Greeks.", tag: "Finance" },
  { slug: "option-payoff", name: "Option Payoff", desc: "Strategy P/L diagrams.", tag: "Finance" },
  { slug: "monte-carlo", name: "Monte Carlo (GBM)", desc: "Price-path distributions.", tag: "Finance" },
  { slug: "efficient-frontier", name: "Efficient Frontier", desc: "Portfolio risk vs return.", tag: "Finance" },
  { slug: "value-at-risk", name: "Value at Risk", desc: "VaR & expected shortfall.", tag: "Finance" },
  { slug: "bond-pricing", name: "Bond Pricing", desc: "Price, yield & duration.", tag: "Finance" },
  { slug: "compound-interest", name: "Compound Interest", desc: "Investment growth over time.", tag: "Finance" },
  { slug: "amortization", name: "Loan Amortization", desc: "Mortgage payment breakdown.", tag: "Finance" },
  { slug: "sir-model", name: "SIR Epidemic", desc: "Outbreak compartment model.", tag: "Biology" },
  { slug: "neuron", name: "Hodgkin-Huxley Neuron", desc: "Action potential spikes.", tag: "Biology" },
  { slug: "lotka-volterra", name: "Lotka-Volterra", desc: "Predator-prey cycles.", tag: "Biology" },
  { slug: "hardy-weinberg", name: "Hardy-Weinberg", desc: "Allele frequency & selection.", tag: "Biology" },
  { slug: "enzyme-kinetics", name: "Enzyme Kinetics", desc: "Michaelis-Menten curves.", tag: "Biology" },
  { slug: "logistic-growth", name: "Logistic Growth", desc: "Population carrying capacity.", tag: "Biology" },
  { slug: "genetic-drift", name: "Genetic Drift", desc: "Wright-Fisher allele drift.", tag: "Biology" },
  { slug: "sequence-alignment", name: "Sequence Alignment", desc: "Needleman-Wunsch DNA.", tag: "Biology" },
  { slug: "beam-deflection", name: "Beam Deflection", desc: "Sag & bending moment.", tag: "Structural" },
  { slug: "column-buckling", name: "Column Buckling", desc: "Euler critical load.", tag: "Structural" },
  { slug: "mohrs-circle", name: "Mohr's Circle", desc: "2D stress transformation.", tag: "Structural" },
  { slug: "shear-moment", name: "Shear & Moment", desc: "SFD/BMD diagrams.", tag: "Structural" },
  { slug: "retaining-wall", name: "Retaining Wall", desc: "Rankine earth pressure.", tag: "Structural" },
  { slug: "base-shear", name: "Seismic Base Shear", desc: "Equivalent lateral force.", tag: "Structural" },
  { slug: "soil-bearing", name: "Soil Bearing", desc: "Terzaghi capacity.", tag: "Structural" },
  { slug: "concrete-beam", name: "Concrete Beam", desc: "RC flexural capacity.", tag: "Structural" },
  { slug: "bode-plot", name: "Bode Plot", desc: "Frequency response.", tag: "Electrical" },
  { slug: "filter-designer", name: "Filter Designer", desc: "RC/RLC filter response.", tag: "Electrical" },
  { slug: "pid-control", name: "PID Controller", desc: "Step-response tuning.", tag: "Electrical" },
  { slug: "transmission-line", name: "Transmission Line", desc: "VSWR & reflections.", tag: "Electrical" },
  { slug: "op-amp", name: "Op-Amp Circuits", desc: "Amplifier configurations.", tag: "Electrical" },
  { slug: "three-phase", name: "Three-Phase Power", desc: "Grid power & phasors.", tag: "Electrical" },
  { slug: "transistor-bias", name: "Transistor Bias", desc: "BJT Q-point load line.", tag: "Electrical" },
  { slug: "aliasing", name: "Sampling & Aliasing", desc: "The Nyquist theorem.", tag: "Electrical" },
  { slug: "hypothesis-test", name: "Hypothesis Test", desc: "p-values & rejection regions.", tag: "Statistics" },
  { slug: "linear-regression", name: "Linear Regression", desc: "Least squares & R².", tag: "Statistics" },
  { slug: "central-limit", name: "Central Limit Theorem", desc: "Means go normal.", tag: "Statistics" },
  { slug: "confidence-interval", name: "Confidence Intervals", desc: "What 95% really means.", tag: "Statistics" },
  { slug: "bayes-inference", name: "Bayesian Inference", desc: "Prior × likelihood → posterior.", tag: "Statistics" },
  { slug: "bootstrap", name: "Bootstrap", desc: "Resampling confidence.", tag: "Statistics" },
  { slug: "pca", name: "PCA", desc: "Axes of maximum variance.", tag: "Statistics" },
  { slug: "ab-test", name: "A/B Test", desc: "Two-proportion significance.", tag: "Statistics" },
  { slug: "forward-kinematics", name: "Forward Kinematics", desc: "Joint angles → end effector.", tag: "Robotics" },
  { slug: "inverse-kinematics", name: "Inverse Kinematics", desc: "Target → joint angles.", tag: "Robotics" },
  { slug: "differential-drive", name: "Differential Drive", desc: "Wheel speeds → path.", tag: "Robotics" },
  { slug: "cart-pole", name: "Cart-Pole Balance", desc: "Inverted pendulum control.", tag: "Robotics" },
  { slug: "quadcopter", name: "Quadcopter Control", desc: "Nested PID flight.", tag: "Robotics" },
  { slug: "rrt", name: "RRT Path Planning", desc: "Sampling-based planner.", tag: "Robotics" },
  { slug: "dc-motor", name: "DC Motor", desc: "Speed-torque & step.", tag: "Robotics" },
  { slug: "kalman-filter", name: "Kalman Filter", desc: "Optimal state estimation.", tag: "Robotics" },
  { slug: "particle-box", name: "Particle in a Box", desc: "Quantized energy levels.", tag: "Quantum" },
  { slug: "quantum-tunneling", name: "Quantum Tunneling", desc: "Through a forbidden barrier.", tag: "Quantum" },
  { slug: "bloch-sphere", name: "Bloch Sphere", desc: "The state of a qubit.", tag: "Quantum" },
  { slug: "hydrogen-orbitals", name: "Hydrogen Orbitals", desc: "Electron probability clouds.", tag: "Quantum" },
  { slug: "special-relativity", name: "Special Relativity", desc: "Time dilation & contraction.", tag: "Quantum" },
  { slug: "photoelectric", name: "Photoelectric Effect", desc: "Einstein's photon.", tag: "Quantum" },
  { slug: "quantum-harmonic", name: "Quantum Harmonic Oscillator", desc: "Evenly-spaced energy ladder.", tag: "Quantum" },
  { slug: "stern-gerlach", name: "Stern-Gerlach", desc: "Spin measurement.", tag: "Quantum" },
  { slug: "harmonic-series", name: "Harmonic Series", desc: "Overtones & timbre.", tag: "Acoustics" },
  { slug: "equal-temperament", name: "Equal Temperament", desc: "Tuning & cents.", tag: "Acoustics" },
  { slug: "chladni", name: "Chladni Plates", desc: "Nodal sand patterns.", tag: "Acoustics" },
  { slug: "helmholtz-resonator", name: "Helmholtz Resonator", desc: "Cavity resonance.", tag: "Acoustics" },
  { slug: "room-modes", name: "Room Modes", desc: "Standing waves in a room.", tag: "Acoustics" },
  { slug: "reverb-time", name: "Reverb Time (Sabine)", desc: "RT60 decay.", tag: "Acoustics" },
  { slug: "sound-levels", name: "Sound Levels (dB)", desc: "Decibel addition & falloff.", tag: "Acoustics" },
  { slug: "additive-synthesis", name: "Additive Synthesis", desc: "Tone from sine waves.", tag: "Acoustics" },
  { slug: "stress-strain", name: "Stress-Strain Curve", desc: "Tensile test to fracture.", tag: "Materials" },
  { slug: "carnot-cycle", name: "Carnot Cycle", desc: "Ideal engine efficiency.", tag: "Materials" },
  { slug: "otto-cycle", name: "Otto Cycle", desc: "Gasoline engine P-V.", tag: "Materials" },
  { slug: "phase-diagram", name: "Phase Diagram", desc: "Solid, liquid, gas.", tag: "Materials" },
  { slug: "thermal-expansion", name: "Thermal Expansion", desc: "Growth with temperature.", tag: "Materials" },
  { slug: "fatigue", name: "Fatigue (S-N)", desc: "Cyclic life to failure.", tag: "Materials" },
  { slug: "entropy", name: "Entropy", desc: "The second law in action.", tag: "Materials" },
  { slug: "thermal-resistance", name: "Thermal Resistance", desc: "R-value composite wall.", tag: "Materials" },
  { slug: "linear-programming", name: "Linear Programming", desc: "Optimize over constraints.", tag: "Optimization" },
  { slug: "knapsack", name: "0/1 Knapsack", desc: "DP value maximization.", tag: "Optimization" },
  { slug: "queueing", name: "M/M/1 Queue", desc: "Queueing theory.", tag: "Optimization" },
  { slug: "eoq", name: "Economic Order Quantity", desc: "Inventory cost optimum.", tag: "Optimization" },
  { slug: "simulated-annealing", name: "Simulated Annealing", desc: "Escape local minima.", tag: "Optimization" },
  { slug: "critical-path", name: "Critical Path (CPM)", desc: "Project scheduling.", tag: "Optimization" },
  { slug: "game-theory", name: "Game Theory (Nash)", desc: "2×2 equilibria.", tag: "Optimization" },
  { slug: "max-flow", name: "Maximum Flow", desc: "Network flow & min cut.", tag: "Optimization" },
  { slug: "shortest-path", name: "Shortest Path", desc: "Dijkstra weighted graph.", tag: "Graph Theory" },
  { slug: "spanning-tree", name: "Spanning Tree", desc: "Kruskal MST.", tag: "Graph Theory" },
  { slug: "graph-coloring", name: "Graph Coloring", desc: "Chromatic number.", tag: "Graph Theory" },
  { slug: "small-world", name: "Small-World Network", desc: "Watts-Strogatz rewiring.", tag: "Graph Theory" },
  { slug: "pagerank", name: "PageRank", desc: "Importance by links.", tag: "Graph Theory" },
  { slug: "bipartite-matching", name: "Bipartite Matching", desc: "Optimal assignment.", tag: "Graph Theory" },
  { slug: "centrality", name: "Network Centrality", desc: "Who matters most.", tag: "Graph Theory" },
  { slug: "graph-traversal", name: "Graph Traversal", desc: "BFS vs DFS.", tag: "Graph Theory" },
  { slug: "supply-demand", name: "Supply & Demand", desc: "Market equilibrium.", tag: "Economics" },
  { slug: "elasticity", name: "Price Elasticity", desc: "Demand sensitivity.", tag: "Economics" },
  { slug: "monopoly", name: "Monopoly Pricing", desc: "Market power & DWL.", tag: "Economics" },
  { slug: "cobb-douglas", name: "Cobb-Douglas", desc: "Optimal input mix.", tag: "Economics" },
  { slug: "lorenz-gini", name: "Lorenz & Gini", desc: "Income inequality.", tag: "Economics" },
  { slug: "laffer-curve", name: "Laffer Curve", desc: "Tax rate vs revenue.", tag: "Economics" },
  { slug: "comparative-advantage", name: "Comparative Advantage", desc: "Gains from trade.", tag: "Economics" },
  { slug: "indifference-curves", name: "Consumer Choice", desc: "Utility maximization.", tag: "Economics" },
  { slug: "airfoil-polar", name: "Airfoil Lift & Drag", desc: "Wing polar & stall.", tag: "Aerospace" },
  { slug: "glide", name: "Glide Performance", desc: "Range from altitude.", tag: "Aerospace" },
  { slug: "rocket-staging", name: "Rocket Staging", desc: "Multi-stage delta-v.", tag: "Aerospace" },
  { slug: "reentry", name: "Atmospheric Reentry", desc: "Heating & g-load.", tag: "Aerospace" },
  { slug: "standard-atmosphere", name: "Standard Atmosphere", desc: "ISA T/P/density.", tag: "Aerospace" },
  { slug: "mach-cone", name: "Mach Cone", desc: "Supersonic shock.", tag: "Aerospace" },
  { slug: "propeller", name: "Propeller Thrust", desc: "Actuator-disk theory.", tag: "Aerospace" },
  { slug: "orbital-elements", name: "Orbital Elements", desc: "Shape of an orbit.", tag: "Aerospace" },
  { slug: "atmospheric-stability", name: "Atmospheric Stability", desc: "CAPE & convection.", tag: "Weather" },
  { slug: "coriolis", name: "Coriolis Effect", desc: "Why winds curve.", tag: "Weather" },
  { slug: "hurricane", name: "Hurricane Model", desc: "Pressure-driven winds.", tag: "Weather" },
  { slug: "wind-chill", name: "Wind Chill & Heat Index", desc: "Apparent temperature.", tag: "Weather" },
  { slug: "psychrometrics", name: "Psychrometrics", desc: "Dew point & wet bulb.", tag: "Weather" },
  { slug: "geostrophic-wind", name: "Geostrophic Wind", desc: "Wind along isobars.", tag: "Weather" },
  { slug: "rossby-waves", name: "Rossby Waves", desc: "Meandering jet stream.", tag: "Weather" },
  { slug: "rankine-vortex", name: "Tornado Vortex", desc: "Rankine wind profile.", tag: "Weather" },
  { slug: "laser-cavity", name: "Laser Cavity", desc: "Gain, loss & threshold.", tag: "Photonics" },
  { slug: "fiber-optics", name: "Fiber Optics", desc: "Total internal reflection.", tag: "Photonics" },
  { slug: "gaussian-beam", name: "Gaussian Beam", desc: "Waist & divergence.", tag: "Photonics" },
  { slug: "polarization", name: "Polarization", desc: "Malus's law.", tag: "Photonics" },
  { slug: "thin-film", name: "Thin-Film Coating", desc: "Anti-reflection interference.", tag: "Photonics" },
  { slug: "single-slit", name: "Single-Slit Diffraction", desc: "Fraunhofer pattern.", tag: "Photonics" },
  { slug: "bragg-mirror", name: "Bragg Mirror", desc: "Dielectric reflector.", tag: "Photonics" },
  { slug: "led", name: "LED Band Gap", desc: "Gap sets the color.", tag: "Photonics" },
  { slug: "binding-energy", name: "Nuclear Binding Energy", desc: "Fusion vs fission.", tag: "Nuclear" },
  { slug: "fission-reactor", name: "Fission Chain Reaction", desc: "Criticality factor k.", tag: "Nuclear" },
  { slug: "fusion-lawson", name: "Fusion (Lawson)", desc: "Triple product ignition.", tag: "Nuclear" },
  { slug: "radiometric-dating", name: "Radiometric Dating", desc: "Isotope clock ages.", tag: "Nuclear" },
  { slug: "radiation-shielding", name: "Radiation Shielding", desc: "Attenuation & HVL.", tag: "Nuclear" },
  { slug: "radiation-dose", name: "Radiation Dose", desc: "Time, distance, shielding.", tag: "Nuclear" },
  { slug: "reactor-kinetics", name: "Reactor Kinetics", desc: "Reactivity & period.", tag: "Nuclear" },
  { slug: "neutron-transport", name: "Neutron Transport", desc: "Random walk & moderation.", tag: "Nuclear" },
  { slug: "solar-panel", name: "Solar PV System", desc: "Panels to kilowatt-hours.", tag: "Energy" },
  { slug: "wind-power", name: "Wind Turbine Power", desc: "Betz-limited power curve.", tag: "Energy" },
  { slug: "hydro-power", name: "Hydroelectric Power", desc: "Head × flow × gravity.", tag: "Energy" },
  { slug: "heat-pump", name: "Heat Pump COP", desc: "Heat moved vs energy in.", tag: "Energy" },
  { slug: "ev-efficiency", name: "EV Range & Efficiency", desc: "Speed vs range.", tag: "Energy" },
  { slug: "battery-storage", name: "Battery Storage", desc: "Usable capacity & backup.", tag: "Energy" },
  { slug: "carbon-footprint", name: "Carbon Footprint", desc: "Annual CO₂ breakdown.", tag: "Energy" },
  { slug: "lcoe", name: "Levelized Cost of Energy", desc: "True $/MWh.", tag: "Energy" },
  { slug: "rsa", name: "RSA Encryption", desc: "Public-key crypto.", tag: "Cryptography" },
  { slug: "diffie-hellman", name: "Diffie-Hellman", desc: "Shared-secret exchange.", tag: "Cryptography" },
  { slug: "classical-ciphers", name: "Classical Ciphers", desc: "Caesar & Vigenère.", tag: "Cryptography" },
  { slug: "hash-avalanche", name: "Hash Avalanche", desc: "One bit changes all.", tag: "Cryptography" },
  { slug: "shannon-entropy", name: "Shannon Entropy", desc: "Info & password strength.", tag: "Cryptography" },
  { slug: "huffman", name: "Huffman Coding", desc: "Optimal compression.", tag: "Cryptography" },
  { slug: "hamming-code", name: "Hamming Code", desc: "Single-error correction.", tag: "Cryptography" },
  { slug: "elliptic-curve", name: "Elliptic Curve", desc: "ECC point addition.", tag: "Cryptography" },
  { slug: "haversine", name: "Great-Circle Distance", desc: "Haversine on a sphere.", tag: "Geospatial" },
  { slug: "map-projection", name: "Map Projection", desc: "Mercator distortion.", tag: "Geospatial" },
  { slug: "gps-trilateration", name: "GPS Trilateration", desc: "Position from distances.", tag: "Geospatial" },
  { slug: "viewshed", name: "Viewshed", desc: "Line-of-sight visibility.", tag: "Geospatial" },
  { slug: "spatial-interpolation", name: "Spatial Interpolation", desc: "IDW surface from samples.", tag: "Geospatial" },
  { slug: "dead-reckoning", name: "Dead Reckoning", desc: "Navigation with drift.", tag: "Geospatial" },
  { slug: "rhumb-line", name: "Rhumb Line", desc: "vs great circle.", tag: "Geospatial" },
  { slug: "point-in-polygon", name: "Point in Polygon", desc: "Ray-casting geofence.", tag: "Geospatial" },
  { slug: "tolerance-stackup", name: "Tolerance Stack-Up", desc: "Worst-case vs RSS.", tag: "Manufacturing" },
  { slug: "process-capability", name: "Process Capability", desc: "Cp / Cpk & defects.", tag: "Manufacturing" },
  { slug: "oee", name: "OEE", desc: "Equipment effectiveness.", tag: "Manufacturing" },
  { slug: "cnc-feeds-speeds", name: "CNC Feeds & Speeds", desc: "Cutting parameters.", tag: "Manufacturing" },
  { slug: "line-balancing", name: "Line Balancing", desc: "Takt time & stations.", tag: "Manufacturing" },
  { slug: "control-chart", name: "SPC Control Chart", desc: "In control or not.", tag: "Manufacturing" },
  { slug: "learning-curve", name: "Learning Curve", desc: "Cost falls with volume.", tag: "Manufacturing" },
  { slug: "littles-law", name: "Little's Law", desc: "WIP = throughput × time.", tag: "Manufacturing" },
  { slug: "elo-rating", name: "Elo Rating", desc: "Win probability & updates.", tag: "Sports" },
  { slug: "pythagorean-expectation", name: "Pythagorean Expectation", desc: "Wins from points.", tag: "Sports" },
  { slug: "marathon-pacing", name: "Marathon Pacing", desc: "Splits & strategy.", tag: "Sports" },
  { slug: "magnus-effect", name: "Magnus Effect", desc: "Spinning ball curve.", tag: "Sports" },
  { slug: "xg-model", name: "Expected Goals (xG)", desc: "Shot quality model.", tag: "Sports" },
  { slug: "win-probability", name: "Win Probability", desc: "Live game odds.", tag: "Sports" },
  { slug: "tournament-bracket", name: "Tournament Odds", desc: "Bracket simulation.", tag: "Sports" },
  { slug: "shot-arc", name: "Basketball Shot Arc", desc: "Optimal release angle.", tag: "Sports" },
  { slug: "dice-probability", name: "Dice Probability", desc: "Sum distributions.", tag: "Probability" },
  { slug: "poker-odds", name: "Poker Odds", desc: "Five-card hand odds.", tag: "Probability" },
  { slug: "roulette", name: "Roulette Edge", desc: "House edge & EV.", tag: "Probability" },
  { slug: "birthday-paradox", name: "Birthday Paradox", desc: "23 people, even odds.", tag: "Probability" },
  { slug: "gamblers-ruin", name: "Gambler's Ruin", desc: "The house always wins.", tag: "Probability" },
  { slug: "monty-hall", name: "Monty Hall", desc: "Always switch.", tag: "Probability" },
  { slug: "law-of-large-numbers", name: "Law of Large Numbers", desc: "Averages converge.", tag: "Probability" },
  { slug: "lottery-odds", name: "Lottery Odds", desc: "Jackpot combinatorics.", tag: "Probability" },
  { slug: "gyroscope", name: "Gyroscope & Precession", desc: "Why a spinning top doesn't fall.", tag: "Physics" },
  { slug: "coupled-oscillators", name: "Coupled Oscillators", desc: "Normal modes and beating.", tag: "Physics" },
  { slug: "driven-resonance", name: "Driven Resonance", desc: "Amplitude near the natural frequency.", tag: "Physics" },
  { slug: "gear-train", name: "Gear Train Ratios", desc: "Trade speed for torque.", tag: "Engineering" },
  { slug: "rolling-motion", name: "Rolling Without Slipping", desc: "Race shapes down a ramp.", tag: "Physics" },
  { slug: "rocket-equation", name: "Rocket Equation", desc: "Tsiolkovsky Δv and staging.", tag: "Aerospace" },
  { slug: "collision-lab", name: "Collision Lab", desc: "Elastic vs inelastic 1D collisions.", tag: "Physics" },
  { slug: "moment-of-inertia", name: "Moment of Inertia", desc: "Rotational mass & parallel-axis.", tag: "Physics" },
  { slug: "pipe-flow", name: "Pipe Flow & Head Loss", desc: "Darcy–Weisbach friction.", tag: "Engineering" },
  { slug: "pump-curve", name: "Pump & System Curves", desc: "Find the operating point.", tag: "Engineering" },
  { slug: "open-channel", name: "Open-Channel Flow", desc: "Manning's equation for rivers.", tag: "Engineering" },
  { slug: "heat-exchanger", name: "Heat Exchanger (LMTD)", desc: "Counter vs parallel flow.", tag: "Engineering" },
  { slug: "compressible-nozzle", name: "Compressible Nozzle Flow", desc: "De Laval nozzle & choking.", tag: "Aerospace" },
  { slug: "bernoulli", name: "Bernoulli / Venturi", desc: "Faster flow, lower pressure.", tag: "Physics" },
  { slug: "fin-cooling", name: "Fin Cooling", desc: "Heat sinks & extended surfaces.", tag: "Engineering" },
  { slug: "pitot-tube", name: "Pitot-Tube Airspeed", desc: "How planes measure speed.", tag: "Aerospace" },
  { slug: "timer-555", name: "555 Timer", desc: "Classic astable oscillator.", tag: "Electrical" },
  { slug: "logic-gates", name: "Logic Gates", desc: "Truth tables for digital gates.", tag: "Electrical" },
  { slug: "binary-adder", name: "Binary Adder", desc: "Ripple-carry addition.", tag: "Electrical" },
  { slug: "bjt-amplifier", name: "BJT Amplifier", desc: "Bias point & voltage gain.", tag: "Electrical" },
  { slug: "active-filter", name: "Active Filter (Bode)", desc: "Frequency response & roll-off.", tag: "Electrical" },
  { slug: "buck-converter", name: "Buck Converter", desc: "Step-down switching regulator.", tag: "Electrical" },
  { slug: "antenna-pattern", name: "Antenna Pattern", desc: "Dipole radiation & directivity.", tag: "Electrical" },
  { slug: "motor-torque-speed", name: "Motor Torque–Speed", desc: "DC motor operating point.", tag: "Electrical" },
  { slug: "titration-curve", name: "Acid–Base Titration", desc: "The pH jump at equivalence.", tag: "Chemistry" },
  { slug: "reaction-equilibrium", name: "Chemical Equilibrium", desc: "ICE table & how far it goes.", tag: "Chemistry" },
  { slug: "nernst-cell", name: "Nernst Equation", desc: "Cell voltage from concentration.", tag: "Chemistry" },
  { slug: "arrhenius-rate", name: "Arrhenius Rate", desc: "Temperature and reaction speed.", tag: "Chemistry" },
  { slug: "solubility", name: "Solubility & Saturation", desc: "How much dissolves vs temperature.", tag: "Chemistry" },
  { slug: "van-der-waals", name: "Van der Waals Gas", desc: "Where the ideal gas law breaks.", tag: "Chemistry" },
  { slug: "buffer-solution", name: "Buffer Solution", desc: "Henderson–Hasselbalch pH.", tag: "Chemistry" },
  { slug: "electrolysis", name: "Electrolysis", desc: "Faraday's laws & electroplating.", tag: "Chemistry" },
  { slug: "pharmacokinetics", name: "Pharmacokinetics", desc: "Drug concentration over time.", tag: "Biology" },
  { slug: "michaelis-menten", name: "Michaelis–Menten", desc: "Enzyme kinetics & saturation.", tag: "Biology" },
  { slug: "windkessel", name: "Windkessel Model", desc: "Arterial pressure waveform.", tag: "Biology" },
  { slug: "cardiac-action-potential", name: "Cardiac Action Potential", desc: "The electrical heartbeat.", tag: "Biology" },
  { slug: "mutation-selection", name: "Mutation–Selection", desc: "Allele frequency evolution.", tag: "Biology" },
  { slug: "phylo-distance", name: "Phylogenetic Distance", desc: "DNA divergence to a tree.", tag: "Biology" },
  { slug: "tumor-growth", name: "Tumor Growth", desc: "Gompertz & logistic dynamics.", tag: "Biology" },
  { slug: "oxygen-dissociation", name: "O₂–Hemoglobin Curve", desc: "How blood loads & unloads O₂.", tag: "Biology" },
  { slug: "bond-duration", name: "Bond Duration", desc: "Interest-rate sensitivity.", tag: "Finance" },
  { slug: "options-greeks", name: "Option Greeks", desc: "Delta, gamma, vega, theta.", tag: "Finance" },
  { slug: "binomial-option", name: "Binomial Option Pricing", desc: "Lattice option valuation.", tag: "Finance" },
  { slug: "capm-beta", name: "CAPM & Beta", desc: "Pricing risk with beta.", tag: "Finance" },
  { slug: "dcf-valuation", name: "DCF Valuation", desc: "Present value of future cash.", tag: "Finance" },
  { slug: "kelly-criterion", name: "Kelly Criterion", desc: "Optimal bet sizing.", tag: "Finance" },
  { slug: "monte-carlo-retirement", name: "Retirement Monte Carlo", desc: "Range of portfolio outcomes.", tag: "Finance" },
  { slug: "dividend-discount", name: "Dividend Discount Model", desc: "Gordon growth valuation.", tag: "Finance" },
  { slug: "pid-tuner", name: "PID Controller Tuner", desc: "Tune Kp, Ki, Kd for a step.", tag: "Robotics" },
  { slug: "root-locus", name: "Root Locus", desc: "Poles moving with gain.", tag: "Robotics" },
  { slug: "step-response", name: "Second-Order Step Response", desc: "Overshoot & settling time.", tag: "Robotics" },
  { slug: "bode-nyquist", name: "Bode Plot", desc: "Magnitude, phase & margins.", tag: "Robotics" },
  { slug: "state-space", name: "State-Space Phase Portrait", desc: "Eigenvalues & stability.", tag: "Robotics" },
  { slug: "lead-lag", name: "Lead–Lag Compensator", desc: "Shaping phase for stability.", tag: "Robotics" },
  { slug: "feedback-loop", name: "Feedback Loop", desc: "Why feedback beats open-loop.", tag: "Robotics" },
  { slug: "second-order-response", name: "Damping Regimes", desc: "Under, critical & overdamped.", tag: "Robotics" },
  { slug: "fir-filter", name: "FIR Filter Designer", desc: "Windowed-sinc low-pass.", tag: "Signals" },
  { slug: "dft-analysis", name: "DFT Spectrum Analysis", desc: "Find hidden frequencies.", tag: "Signals" },
  { slug: "window-functions", name: "Window Functions", desc: "Taming spectral leakage.", tag: "Signals" },
  { slug: "quantization-noise", name: "ADC Quantization", desc: "Bits, levels & SNR.", tag: "Signals" },
  { slug: "am-fm-modulation", name: "AM / FM Modulation", desc: "How radio carries sound.", tag: "Signals" },
  { slug: "matched-filter", name: "Matched Filter", desc: "Pull signal out of noise.", tag: "Signals" },
  { slug: "sampling-theorem", name: "Sampling & Nyquist", desc: "Aliasing and the Nyquist rate.", tag: "Signals" },
  { slug: "pole-zero", name: "Pole–Zero Response", desc: "Poles peak, zeros notch.", tag: "Signals" },
  { slug: "perceptron", name: "Perceptron", desc: "The simplest learning machine.", tag: "CS / AI" },
  { slug: "kmeans-cluster", name: "k-Means Clustering", desc: "Find groups in data.", tag: "CS / AI" },
  { slug: "decision-tree", name: "Decision Tree", desc: "Carve space into boxes.", tag: "CS / AI" },
  { slug: "knn-classifier", name: "k-Nearest Neighbors", desc: "Classify by your neighbors.", tag: "CS / AI" },
  { slug: "logistic-regression", name: "Logistic Regression", desc: "Probability from a line.", tag: "CS / AI" },
  { slug: "svm-margin", name: "SVM Maximum Margin", desc: "The widest separating street.", tag: "CS / AI" },
  { slug: "naive-bayes", name: "Naive Bayes", desc: "Classification by probability.", tag: "CS / AI" },
  { slug: "q-learning", name: "Q-Learning Gridworld", desc: "Learning to reach a goal.", tag: "CS / AI" },
];

export default function StudioIndex() {
  return (
    <div className="mx-auto max-w-6xl px-4 py-10">
      <JsonLd data={softwareAppLd({ name: "PolySim Studio", description: "Browser-native simulation studio.", path: "/studio" })} />
      <Breadcrumbs items={[{ name: "Home", path: "/" }, { name: "Studio", path: "/studio" }]} />
      <h1 className="text-3xl font-black tracking-tight text-slate-900 dark:text-slate-100 sm:text-4xl">
        PolySim Studio
      </h1>
      <p className="mt-3 max-w-2xl text-lg text-slate-600 dark:text-slate-400">
        Real simulations that run entirely in your browser — no install, no account, free forever locally.
        Pick an engine and start exploring.
      </p>

      <StudioBrowser sims={SIMS} />

      <ProductGrid products={contextualProducts("studio", 6)} title="Power up your workspace" />
      <Disclaimer />
    </div>
  );
}
